MagicFlex Integration Tile
DataDog/integrations-extras pull request #1017
Opened 2021-10-06 14:10 UTC by AlexMagicFlex

### What does this PR do?

Adding MagicFlex integration tile

### Motivation

What inspired you to submit this pull request?

2021-10-06 19:25 UTC, cswatt requested changes
editorial review

2021-10-06 19:25 UTC, cswatt commented on magicflex/README.md
> +![MagicFlex Dashboard](images/datadog.png)
MagicFlex alerts appear in the Datadog event stream.

2021-11-02 22:37 UTC, ChristineTChen commented
Hi @AlexMagicFlex ,

Have you had a chance to address the above suggestions/feedback?

2021-11-16 18:04 UTC, alexvetras commented on magicflex/README.md
> +[1]: http://https://www.magicflexsoftware.com/
```suggestion
[1]: https://www.magicflexsoftware.com/
```

2022-05-31 14:23 UTC, closed without merging