update doc for squadcast integration
DataDog/integrations-extras pull request #1068
Opened 2021-11-09 04:05 UTC by punit-squadcast

Hi There! 
I am Product solution engineer at Squadcast. We feel that doc needs to be updated for Squadcast integration. Changes has been made, Please review and merge it. 
Thanks & Regards,
Punit

### What does this PR do?

We feel that doc needs to be updated for Squadcast integration

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

attaching screenshot for second image ([2]) available in doc
<img width="462" alt="datadog-webhook" src="https://user-images.githubusercontent.com/87639260/140860015-e191c11e-1853-4fa4-b880-913bfe7ac2c4.png">

2021-11-11 11:28 UTC, hithwen commented
Hallo, this PR is a draft, is that intended?

2021-11-11 16:31 UTC, ruthnaebeck requested changes
Docs review

2021-11-11 16:31 UTC, ruthnaebeck commented on squadcast/README.md
> +Use the Datadog-Squadcast integration to send Datadog alerts/incidents to Squadcast and seamlessly take actions on them within Squadcast.
```suggestion
Use the Datadog-Squadcast integration to send Datadog alerts or incidents to Squadcast and seamlessly take actions on them within Squadcast.
```

2021-11-11 16:31 UTC, ruthnaebeck commented on squadcast/README.md
> +- Trigger, route and resolve alerts/incidents from Datadog
```suggestion
- Trigger, route, and resolve alerts or incidents from Datadog
```

2021-11-11 16:31 UTC, ruthnaebeck commented on squadcast/README.md
> +- Tackle alerts/incidents and set up Escalation Policies as they occur
```suggestion
- Tackle alerts or incidents and set up escalation policies as they occur
```

2021-11-11 16:31 UTC, ruthnaebeck commented on squadcast/README.md
> +- Define on-call Schedules and set up customisable reminders of who is on-call
```suggestion
- Define on-call schedules and set up customizable reminders of who is on-call
```

2021-11-11 16:31 UTC, ruthnaebeck commented on squadcast/README.md
> +**Note**: Only Squadcast users with the right Team-level privileges can configure Services in Squadcast. At least one Escalation Policy must be configured before a Service can be added.
```suggestion
**Note**: Only Squadcast users with the correct team-level privileges can configure services in Squadcast. At least one escalation policy must be configured before a service can be added.
```

2021-11-11 16:31 UTC, ruthnaebeck commented on squadcast/README.md
> +1. Choose the **Team** from the Team-picker on the top.
```suggestion
1. Choose the **Team** from the team-picker on the top.
```

2021-11-11 16:31 UTC, ruthnaebeck commented on squadcast/README.md
> +3. Choose an existing Service, or create a new Service by clicking on Add Service.
```suggestion
3. Choose an existing service, or create a new service by clicking on **Add Service**.
```

2021-11-11 16:31 UTC, ruthnaebeck commented on squadcast/README.md
> +**Note**: Once the Webhook for Squadcast has been configured, ensure that the same is also selected as a channel within Notify your team in the Monitor’s configuration.
```suggestion
**Note**: Once the Webhook for Squadcast has been configured, ensure that the same is also selected as a channel under "Notify your team" in the Monitor’s configuration.
```

2021-11-12 11:50 UTC, punit-squadcast commented
> Hallo, this PR is a draft, is that intended?

yes!

2021-11-15 20:13 UTC, yzhan289 reviewed
LGTM, just 1 suggestion

2021-11-15 20:13 UTC, yzhan289 commented on squadcast/README.md
> +   (b) Paste the **Datadog Webhook URL** provided by Squadcast in the URL field.
```suggestion
   (b) Paste the **Datadog Webhook URL** provided by Squadcast in the **URL** field.
```
to be consistent with `Name` field in bold.

2021-11-18 16:07 UTC, yzhan289 approved these changes

2021-11-24 16:19 UTC, ruthnaebeck approved these changes
👍  for docs

2021-11-25 15:53 UTC, merged

2021-11-26 03:23 UTC, punit-squadcast commented
Hey! Only Screenshot is updated, content are not in https://docs.datadoghq.com/integrations/squadcast/ , could you please have a look to this?

2021-11-28 03:31 UTC, yzhan289 commented
@punit-squadcast, thanks for letting us know! Looks like it is updated now. 👍