RedisEnterprise - Enable collection of Active/Active metrics
DataDog/integrations-extras pull request #1069
Opened 2021-11-10 17:15 UTC by maguec

### What does this PR do?

Enable collection of Redis Enterprise Active/Active metrics

### Motivation

- Give more visitility in various Redis Enterprise use cases
- Remove a dependency on python requests for the Datadog http wrapper
### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [X] Feature or bugfix has tests
- [X] Git history is clean
- [X] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Bumped minor version for new features and CHANGELOG is also updated

2021-11-11 11:32 UTC, hithwen commented
Hallo @maguec, thanks for your contribution. It looks like your branch has conflicts with master, can you please address those?

2021-11-11 13:14 UTC, maguec commented
@hithwen  resoved the conflict

2021-11-11 20:17 UTC, ruthnaebeck requested changes
Docs review

2021-11-11 20:17 UTC, ruthnaebeck commented on redisenterprise/README.md
> +Contact the [Redis Field Engineering Team][11]
```suggestion
Contact the [Redis Field Engineering Team][11].
```

2021-11-11 20:17 UTC, ruthnaebeck commented on redisenterprise/metadata.csv
> +redisenterprise.crdt_egress_bytes,gauge,,byte,,Bytes being sent to CRDT peer,0,redis_enterprise,Redis Enterprise Database Peer Bytes Sent
```suggestion
redisenterprise.crdt_egress_bytes,gauge,,byte,,The bytes being sent to the CRDT peer,0,redis_enterprise,Redis Enterprise Database Peer Bytes Sent
```

2021-11-11 20:17 UTC, ruthnaebeck commented on redisenterprise/metadata.csv
> +redisenterprise.crdt_egress_bytes_decompressed,gauge,,byte,,Decompressed bytes being sent to CRDT peer,0,redis_enterprise,Redis Enterprise Database Peer Bytes Sent Decompressed
```suggestion
redisenterprise.crdt_egress_bytes_decompressed,gauge,,byte,,The decompressed bytes being sent to the CRDT peer,0,redis_enterprise,Redis Enterprise Database Peer Bytes Sent Decompressed
```

2021-11-11 20:17 UTC, ruthnaebeck commented on redisenterprise/metadata.csv
> +redisenterprise.crdt_ingress_bytes,gauge,,byte,,Bytes being received from CRDT peer,0,redis_enterprise,Redis Enterprise Database Peer Bytes Received
```suggestion
redisenterprise.crdt_ingress_bytes,gauge,,byte,,The bytes being received from the CRDT peer,0,redis_enterprise,Redis Enterprise Database Peer Bytes Received
```

2021-11-11 20:17 UTC, ruthnaebeck commented on redisenterprise/metadata.csv
> +redisenterprise.crdt_ingress_bytes_decompressed,gauge,,byte,,Decompressed bytes being received from CRDT peer,0,redis_enterprise,Redis Enterprise Database Peer Bytes Received Decompressed
```suggestion
redisenterprise.crdt_ingress_bytes_decompressed,gauge,,byte,,The decompressed bytes being received from the CRDT peer,0,redis_enterprise,Redis Enterprise Database Peer Bytes Received Decompressed
```

2021-11-11 20:17 UTC, ruthnaebeck commented on redisenterprise/metadata.csv
> +redisenterprise.crdt_local_lag,gauge,,second,,Local lag in CRDT applies,0,redis_enterprise,Redis Enterprise CRDT lag
```suggestion
redisenterprise.crdt_local_lag,gauge,,second,,The local lag in the CRDT applies,0,redis_enterprise,Redis Enterprise CRDT lag
```

2021-11-11 20:17 UTC, ruthnaebeck commented on redisenterprise/metadata.csv
> +redisenterprise.crdt_pending_max,gauge,,item,,Local pending writes in CRDT max,0,redis_enterprise,Redis Enterprise CRDT Pending Max
```suggestion
redisenterprise.crdt_pending_max,gauge,,item,,The local pending writes in the CRDT max,0,redis_enterprise,Redis Enterprise CRDT Pending Max
```

2021-11-11 20:17 UTC, ruthnaebeck commented on redisenterprise/metadata.csv
> +redisenterprise.crdt_pending_min,gauge,,item,,Local pending writes in CRDT min,0,redis_enterprise,Redis Enterprise CRDT Pending Min
```suggestion
redisenterprise.crdt_pending_min,gauge,,item,,The local pending writes in the CRDT min,0,redis_enterprise,Redis Enterprise CRDT Pending Min
```

2021-11-11 22:59 UTC, fanny-jiang approved these changes

2021-11-11 23:00 UTC, fanny-jiang commented
@ruthnaebeck 👍🏼  on the docs side?

2021-11-15 20:16 UTC, apigirl approved these changes

2021-11-15 20:33 UTC, merged

2021-11-16 14:28 UTC, yzhan289 commented
Thanks for the PR. I just merged this in and am working on getting it updated on Datadog.

2021-11-16 14:54 UTC, yzhan289 commented
Hi @maguec, the dashboard is currently not able to show up on Datadog since the file was not added to `manifest.json`. I have made a PR adding it: https://github.com/DataDog/integrations-extras/pull/1076