Add Twenty Forty Eight app
DataDog/integrations-extras pull request #1103
Opened 2021-12-10 22:47 UTC by nmuldavin

### What does this PR do?

Add Twenty Forty Eight app

This app is built and maintained by us, Datadog, although we used an open-source react project

2021-12-13 19:38 UTC, jsonmercer requested changes

2021-12-13 19:38 UTC, jsonmercer commented on twenty_forty_eight/README.md
> +Twenty Forty Eight is an easy and fun game you can add to your Datadog dashboards. This fun extension is made possible by [Datadog apps](https://docs.datadoghq.com/developers/datadog_apps) including
I would rewrite the second and third sentences to this: "This fun extension is made possible by [Datadog apps] (https://docs.datadoghq.com/developers/datadog_apps), which can enhance the user experience by adding 3rd-party content not supported natively within Datadog. If you are interested in enhancing your Datadog experience, we encourage you to build an app of your own."

2021-12-13 19:38 UTC, jsonmercer commented on twenty_forty_eight/README.md
> +1. In your Datadog account, navigate to Dashboards. Select the dashboard that you would like to add the Game to, or [create a new dashboard](https://docs.datadoghq.com/dashboards/#new-dashboard).
"Game" doesn't need to be capitalized.

2021-12-13 19:38 UTC, jsonmercer commented on twenty_forty_eight/README.md
> +[Contact Datadog support](https://www.datadoghq.com/support/) if you run in to any issues.
"in to" should be "into"

2021-12-13 20:16 UTC, sarina-dd commented on twenty_forty_eight/README.md
> +Twenty Forty Eight is an easy and fun game you can add to your Datadog dashboards. This fun extension is made possible by [Datadog apps](https://docs.datadoghq.com/developers/datadog_apps) including
```suggestion
Twenty Forty Eight is a fun game you can add to your Datadog dashboards. This extension is made possible by [Datadog apps][1] which extends the user-interface with third party content not supported natively. If you are interested in extending your Datadog experience for business or for fun, you can [build out an app or game of your own][1].
```

2021-12-16 23:48 UTC, nmuldavin commented
Issues should be addressed thanks for the feedback

2022-01-18 16:10 UTC, mgarabed approved these changes

2022-01-18 16:10 UTC, merged