Setting up codescanning for integrations-extras
DataDog/integrations-extras pull request #1115
Opened 2022-01-03 22:17 UTC by ganeshkumarsv

Static code analysis on integrations-extras using Github's Code Scanning.

This PR has Github workflow configs to trigger the Code Scanning on every PR and on push to master branch. As of now only default security based CodeQL queries are configured. We can gradually add queries for Code Quality later. It is a part of Datadog compliance requirements to regularly perform code-scanning on all the customer installed code. As the repository is small, no security alerts were found during the scan.

2022-01-25 15:14 UTC, yzhan289 requested changes
Thanks for the PR! Can you also add something similar to https://github.com/DataDog/integrations-core/pull/10963/files#diff-5f817878eaf9204edc264b31f944926a01e44b11f34131257be3d84c20f8f51fR3 for `paths-ignore`?

2022-01-25 15:14 UTC, yzhan289 commented on .github/workflows/codeql-analysis.yml
> +        language: [ 'python', 'ruby' ]
This repo should only have python files
```suggestion
        language: [ 'python' ]
```

2022-02-14 18:23 UTC, ganeshkumarsv commented
@yzhan289 No alerts have been detected on the scan that we ran, so I don't think `paths-ignore` is necessary right now. In case if we notice some alerts coming from any of the test or lib directories, we can add them later.

2022-02-14 18:55 UTC, yzhan289 approved these changes

2022-02-14 19:11 UTC, merged