Update the regions text in auth0 setup steps to include new regions
DataDog/integrations-extras pull request #1137
Opened 2022-01-31 22:55 UTC by patrickkang

### What does this PR do?

Update the regions text in auth0 setup steps to describe the new regions supported.

### Motivation
With additional regions being added to auth0 log streams, the text needed some updates.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-02-01 10:59 UTC, hithwen commented
Hallo @patrickkang this PR is a draft, I just want to make sure that that's on purpose. Please, let us know when the PR is ready for review

2022-02-03 20:31 UTC, patrickkang commented
Hi @hithwen, I marked it as a draft intentionally, but it's ready for review now. Thanks!

2022-02-03 21:02 UTC, sarah-witt approved these changes

2022-02-03 21:04 UTC, maycmlee requested changes

2022-02-03 21:04 UTC, maycmlee commented on auth0/README.md
> +[7]: https://docs.datadoghq.com/api/latest/logs/#send-logs
```suggestion
[7]: https://docs.datadoghq.com/getting_started/site/
```

2022-02-03 21:04 UTC, maycmlee commented on auth0/README.md
> +    | `Region` 		     | The region in which your Datadog site is in (ex. `EU` for app.datadoghq.eu, `US1` for app.datadoghq.com and `US3` for us3.datadoghq.com). For more information, see the relevan
Hi! I changed the link to go to the Datadog site page.

2022-02-04 22:09 UTC, maycmlee reviewed
Ah sorry, missed a small edit.

2022-02-04 22:09 UTC, maycmlee commented on auth0/README.md
> +    | `Region` 		     | Your [Datadog site][7]. For example, `EU` for app.datadoghq.eu, `US1` for app.datadoghq.com, and `US3` for us3.datadoghq.com). |
```suggestion
    | `Region` 		     | Your [Datadog site][7]. For example, `EU` for app.datadoghq.eu, `US1` for app.datadoghq.com, and `US3` for us3.datadoghq.com. |
```

2022-02-04 22:11 UTC, maycmlee approved these changes

2022-02-04 22:15 UTC, merged