Update Zabbbix documentation with more accurate instructions to use the webhook
DataDog/integrations-extras pull request #1139
Opened 2022-02-03 16:02 UTC by sysy6r

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

This impact the zabbix documentation page : https://docs.datadoghq.com/fr/integrations/zabbix/

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-02-03 16:21 UTC, maycmlee requested changes

2022-02-03 16:21 UTC, maycmlee commented on zabbix/README.md
> +2. Add paramters to the webhook using Zabbix template variables : Add your Datadog api_key and, and the following Zabbix template variables as parameters:
```suggestion
2. Add parameters to the webhook using Zabbix template variables. Add your Datadog api_key and the following Zabbix template variables as parameters:
```

2022-02-03 16:21 UTC, maycmlee commented on zabbix/README.md
> +   ```
Can we put this info into a table instead?

2022-02-03 16:21 UTC, maycmlee commented on zabbix/README.md
> +        api_key | "Enter Yours"
```suggestion
        api_key | Your Datadog API key
```

2022-02-17 22:16 UTC, fanny-jiang commented
Thanks for opening this PR! Looks like the `conf.yaml.example` is out of sync since this [change](https://github.com/DataDog/integrations-extras/pull/1147) was merged. Can you please run `ddev -e validate config zabbix -s` to sync the config file?

2022-04-27 15:41 UTC, merged