Changed to version 4.1 and added an Only AMI count support
DataDog/integrations-extras pull request #1145
Opened 2022-02-09 16:39 UTC by eliadeini

### What does this PR do?

This PR changes titles of the 2 version 4.0  dashboards to version 4.1 and adds an Only-AMI count support.

### Motivation

What inspired you to submit this pull request?
Moving to a new CPM version + an Only AMI support bug

### Review checklist

- [ X ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ X ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-02-09 22:43 UTC, urseberry reviewed
I don't have enough time to complete this review today, so it will go into the Docs team editorial review process. Someone will pick it up on Thursday afternoon. https://datadoghq.atlassian.net/browse/DOCS-3132

2022-02-11 00:31 UTC, sarina-dd requested changes

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +1.	##### Install the [Python Integration][1]
```suggestion
1. Install the [Python Integration][1].
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +2.  ##### Enable support for Datadog on your N2WS instance:
```suggestion
2.  Enable support for Datadog on your N2WS instance:
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +3.	##### Install the Datadog Agent on your N2WS Instance.
```suggestion
3. Install the Datadog Agent on your N2WS Instance.
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +4.	##### Setup Datadog Dashboard metrics
```suggestion
4. Setup Datadog Dashboard metrics
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +5.	##### Get N2WS dashboards
```suggestion
5. Get N2WS dashboards
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +    In [Datadog Integrations][3] , search for 'N2WS' tile and install it.
```suggestion
    In [Datadog Integrations][3], search for 'N2WS' tile and install it. 
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +    You will get 5 types of dashboards to your account, 3 for N2WS Backup & Recovery v3.2.1 (only AWS supported) and 2 for for N2WS Backup & Recovery v4.1 (includes Azure):
```suggestion
    This integration has five different dashboards available:
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +    'N2WSBackup&Recovery-Graphicalversion', 'N2WSBackup&Recovery-Graphicalversion-areas' and 'N2WSBackup&Recovery-EntitiesSpecificDashboard' for version 3.2.1
```suggestion
    'N2WSBackup&Recovery-Graphicalversion', 'N2WSBackup&Recovery-Graphicalversion-areas' and 'N2WSBackup&Recovery-EntitiesSpecificDashboard' for N2WS Backup & Recovery v3.2.1. **Note**: These dashboards are only available for AWS users.
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +	'N2WSBackup&Recovery-EntitiesSpecificDashboardV4.1' and 'N2WSBackup&Recovery-GraphicalVersionV4.1' for version 4.1
```suggestion
	'N2WSBackup&Recovery-EntitiesSpecificDashboardV4.1' and 'N2WSBackup&Recovery-GraphicalVersionV4.1' for N2WS Backup & Recovery v4.1. These dashboards are available for both AWS and Azure.
```

2022-02-11 00:31 UTC, sarina-dd commented on n2ws/README.md
> +    Alternatively users can [import JSON templates from N2WS][4].
```suggestion
    Alternatively, you can [import JSON templates from N2WS][4] to create a dashboard.
```

2022-02-13 09:39 UTC, eliadeini commented on n2ws/README.md
> +2.  ##### Enable support for Datadog on your N2WS instance:
Hi, I've added a fix.

2022-02-13 09:40 UTC, eliadeini commented on n2ws/README.md
> +3.	##### Install the Datadog Agent on your N2WS Instance.
Hi, I've added a fix.

2022-02-13 09:40 UTC, eliadeini commented on n2ws/README.md
> +5.	##### Get N2WS dashboards
Hi, I've added a fix.

2022-02-13 09:40 UTC, eliadeini commented on n2ws/README.md
> +    You will get 5 types of dashboards to your account, 3 for N2WS Backup & Recovery v3.2.1 (only AWS supported) and 2 for for N2WS Backup & Recovery v4.1 (includes Azure):
Hi, I've added a fix.

2022-02-13 09:40 UTC, eliadeini commented on n2ws/README.md
> +	'N2WSBackup&Recovery-EntitiesSpecificDashboardV4.1' and 'N2WSBackup&Recovery-GraphicalVersionV4.1' for version 4.1
Hi, I've added a fix.

2022-02-13 12:36 UTC, closed without merging