[DataZoom] new integration
DataDog/integrations-extras pull request #1262
Opened 2022-04-07 18:00 UTC by ls339

### What does this PR do?

New integration tile and OOTB dashboard for `datazoom` 

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-04-07 18:32 UTC, BoyangHuang approved these changes

2022-04-07 18:36 UTC, ls339 commented on datazoom/manifest.json
> +  "is_public": false,
Not yet GA.

2022-04-07 21:21 UTC, cswatt requested changes
left some comments to clean up the readme

2022-04-07 21:21 UTC, cswatt commented on datazoom/README.md
> +# Agent Check: datazoom
```suggestion
# Agent Check: Datazoom
```

2022-04-07 21:21 UTC, cswatt commented on datazoom/README.md
> +The [Datazoom Datadog Connector][1] sends Collector data to a configured Datadog destination, available for query in Log Explorer.
```suggestion
Datazoom is a video data platform that gathers data from endpoints through an ecosystem of collectors.

The [Datazoom Datadog Connector][1] sends collector data to Datadog, where you can query the data in your [Log Explorer][3].

Datazoom sends data set at the INFO level.
```

2022-04-07 21:21 UTC, cswatt commented on datazoom/README.md
> +[2]: https://docs.datadoghq.com/help/
```suggestion
[2]: https://docs.datadoghq.com/help/
[3]: https://app.datadoghq.com/logs
[4]: https://app.datadoghq.com/dashboard/lists/preset/3?q=datazoom
```

2022-04-07 21:21 UTC, cswatt commented on datazoom/README.md
> +Datazoom logs dashboard is available [here](../dashboard/lists/preset/3?q=datazoom).
```suggestion
See the [Datazoom logs dashboard][4].
```

2022-04-07 21:21 UTC, cswatt commented on datazoom/README.md
> +The Datazoom integration emits logs to Datadog.
```suggestion
The Datazoom integration emits logs to Datadog. No installation is required on the Datadog side.
```

2022-04-07 21:21 UTC, cswatt commented on datazoom/README.md
> +- Visit Datazoom's integation [documentation][1].
```suggestion
- Visit Datazoom's integation [documentation][1] for details on how to configure the Datazoom Datadog Connector.
```

2022-04-14 15:07 UTC, cswatt approved these changes

2022-04-20 14:55 UTC, merged