How to find the `<INTEGRATION_VERSION>`
DataDog/integrations-extras pull request #1291
Opened 2022-04-29 20:56 UTC by wootangly

Clarifying how to find the `<INTEGRATION_VERSION>` for PureStorage through the CHANGELOG.md (https://github.com/DataDog/integrations-extras/blob/master/purefa/CHANGELOG.md).  

This may apply for all the integration-extras which doesn't specify in the main documentation (https://docs.datadoghq.com/agent/guide/use-community-integrations/?tab=agentv721v621).

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-04-29 21:00 UTC, yzhan289 requested changes

2022-04-29 21:00 UTC, yzhan289 commented on purefa/README.md
> +#### Agent Host
```suggestion
#### Host
```

This is a standardized title for README.

2022-04-29 21:00 UTC, yzhan289 commented on purefa/README.md
> +Note:  `<INTEGRATION_VERSION>` can be found within the [CHANGELOG.md](https://github.com/DataDog/integrations-extras/blob/master/purefa/CHANGELOG.md) for Datadog Integration Extras.
You can move `https://github.com/DataDog/integrations-extras/blob/master/purefa/CHANGELOG.md` to the bottom of the README and turn it into `[13]`.

2022-04-29 21:29 UTC, wootangly reviewed
moved to [13]

2022-05-02 13:47 UTC, yzhan289 approved these changes

2022-05-02 14:02 UTC, merged