Add RUM integration for Android
DataDog/integrations-extras pull request #1347
Opened 2022-06-20 08:07 UTC by milena-markovic

### What does this PR do?

Adds Datadog RUM integration tile for Android apps.

### Motivation

Surfacing the existing Android-RUM integration

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-06-20 11:03 UTC, hithwen commented on android/manifest.json
> +    ""
```suggestion
    "log collection"
```

2022-06-20 19:35 UTC, kayayarai commented
Opened https://datadoghq.atlassian.net/browse/DOCS-3655 to track editorial review

2022-06-22 00:43 UTC, alai97 approved these changes

2022-06-27 19:50 UTC, alai97 commented on android/README.md
> +[2]: https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces?tab=androidrum#setup-rum
```suggestion
[2]: https://docs.datadoghq.com/real_user_monitoring/android/?tabs=kotlin#setup
```

2022-06-29 11:14 UTC, hithwen requested changes
> The `validations` job has failed; please review the `Files changed` tab for possible suggestions to resolve.

Please, look at and address the validation failures

2022-06-29 21:36 UTC, milena-markovic commented
> > The `validations` job has failed; please review the `Files changed` tab for possible suggestions to resolve.
> 
> Please, look at and address the validation failures

My bad - I thought it had passed when I re-requested review. I've fixed one, but I'm not sure how to go about the error
`The tile description is 73 characters long. It should be no longer than 80 characters.` since it's already shorter than 80 characters?

2022-06-30 08:52 UTC, hithwen commented
I'm also thinking we should probably rename the folder and integration_id to android_rum, just in case we have another sort of android integration in the fugure

2022-07-04 10:08 UTC, hithwen approved these changes

2022-07-20 13:33 UTC, merged