Add F5 XC integration tile
DataDog/integrations-extras pull request #1558
Opened 2022-10-04 17:46 UTC by gregcoward

### What does this PR do?

This PR is intended to add in an additional integration tile for F5 Distributed Cloud Services

### Motivation

Integration work

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-10-04 17:47 UTC, gregcoward commented
Add integration for F5 Distributed Cloud Services

2022-10-04 22:17 UTC, buraizu commented
Thanks, created DOCS-4173 to track this internally as an editorial review.

2022-10-06 13:51 UTC, yzhan289 requested changes
Thanks for the PR! Can you also add the integration to the `CODEOWNERS` file: https://github.com/DataDog/integrations-extras/blob/master/.github/CODEOWNERS

2022-10-06 13:51 UTC, yzhan289 commented on f5-distributed-cloud/README.md
> +Learn more about [F5 Distributed Cloud Services](https://www.f5.com/cloud).
Small nit, but you can change this link to the reference-style link

2022-10-06 13:52 UTC, yzhan289 commented on f5-distributed-cloud/dashboards/f5xc_access.json
> +    "description": "## Title\n\nDescribe this dashboard. Add links to other dashboards, monitors, wikis,  and docs to help your teammates. Markdown is supported.\n\n- [This might link to a dashboard]
Can you update this `description`?

2022-10-06 16:18 UTC, gregcoward commented on f5-distributed-cloud/dashboards/f5xc_access.json
> +    "description": "## Title\n\nDescribe this dashboard. Add links to other dashboards, monitors, wikis,  and docs to help your teammates. Markdown is supported.\n\n- [This might link to a dashboard]
done

2022-10-06 16:48 UTC, gregcoward commented
Hello,  I have made the reqeuested modifications and will submit a new pull request

2022-10-06 16:48 UTC, closed without merging