OAuth configuration steps updated
DataDog/integrations-extras pull request #1582
Opened 2022-10-26 13:17 UTC by prateeksainilambdatest

### What does this PR do?

OAuth configuration steps updated

2022-10-26 13:58 UTC, anawishnoff commented on lambdatest/README.md
>  3. Click on integrations under settings.
When a user clicks "Connect Accounts" on the datadog tile, they'll be taken to the onboarding_url that you specified when creating the OAuth client, which I believe is this Lambdatest integrations page. If so, we can remove lines 28-30 and replace with the following:

```suggestion
1. Click "Connect Accounts" to begin authorization of the LambdaTest integration. You will be taken to the Integrations page in LambdaTest.
```

2022-10-26 13:59 UTC, anawishnoff commented on lambdatest/README.md
>  4. To integrate Datadog, click on install next to Push to Datadog.
```suggestion
2. In LambdaTest, click "Install" next to **Push to Datadog**. 
```

2022-10-26 13:59 UTC, anawishnoff commented on lambdatest/README.md
> +5. Click on Authorize button to complete the integration process.
```suggestion
5. Click **Authorize** to complete the integration process.
```

2022-10-26 13:59 UTC, anawishnoff commented on lambdatest/README.md
>  6. A confirmation email is sent. Confirm the integration in the email.
```suggestion
6. A confirmation email is sent once the integration configuration is complete.
```

2022-10-26 16:15 UTC, prateeksainilambdatest commented on lambdatest/README.md
>  4. To integrate Datadog, click on install next to Push to Datadog.
Updated accordingly

2022-10-26 16:22 UTC, bgoldberg122 approved these changes

2022-10-26 18:25 UTC, anawishnoff commented on lambdatest/README.md
> +2. Log in to your LambdaTest account on the LambdaTest website and you'll be redirected to your Datadog application.
```suggestion
2. Log in to your LambdaTest account on the LambdaTest website and you'll be redirected to the Datadog authorization page.
```

2022-10-26 18:26 UTC, anawishnoff approved these changes

2022-10-26 18:51 UTC, buraizu requested changes
Thanks, just made some suggestions for consistency and to better align with our [style guide](https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md).

2022-10-26 19:07 UTC, anawishnoff commented on lambdatest/README.md
```suggestion

### Uninstallation

To ensure this integration is fully uninstalled, revoke authorization in the Configure tab of this tile or in [OAuth Apps](https://app.datadoghq.com/organization-settings/oauth-applications) within Organization Settings in Datadog. 

Additionally, ensure that all API keys associated with this integration have been disabled by searching for the integration name on the [API Keys management page](https://app.datadoghq.com/organization-settings/api-keys).
```

Please also add these OAuth-specific instructions under the Configuration section. Thanks!

2022-10-27 12:43 UTC, anawishnoff approved these changes
This is good to go, thanks @prateeksainilambdatest !

2022-10-27 13:56 UTC, FlorentClarret approved these changes

2022-10-27 15:01 UTC, buraizu requested changes

2022-10-27 15:01 UTC, buraizu commented on lambdatest/README.md
> +2. Log in to your LambdaTest account on the LambdaTest website and you'll be redirected to the Datadog authorization page.
```suggestion
2. Log in to your LambdaTest account on the LambdaTest website to be redirected to the Datadog authorization page.
```

2022-10-27 15:01 UTC, buraizu commented on lambdatest/README.md
> +2. Log in to your LambdaTest account on the LambdaTest website and you'll be redirected to the Datadog authorization page.
Please remove the future tense here as mentioned in our style guide:
https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md#tense

2022-10-28 13:15 UTC, merged