Loadrunner integration
DataDog/integrations-extras pull request #1604
Opened 2022-11-14 14:31 UTC by mihneavelin

### What does this PR do?

Micro Focus LoadRunner Professional tile only listing.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-11-14 17:46 UTC, hestonhoffman commented
Hi! I've opened up an [editorial review ticket](https://datadoghq.atlassian.net/browse/DOCS-4387) for the documentation team.

2022-11-16 22:50 UTC, buraizu requested changes
Thanks for implementing those changes. I set this up in a local build and noticed a few additional styling/formatting issues. For example, sub-steps within a step were not indented. 

These suggestions should correct those issues, and also further clarify some sections which could cause confusion for users due to overlap with Datadog features (for example, Datadog also offers monitors, so I updated the title of the `To setup the Datadog monitor` section to clarify).

Thank you for your patience, and please let me know if you have any questions.

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +The measurements are displayed in the **Resource Measurements** pane of the Datadog dialog box.
```suggestion
   ![snapshot][4]

   - Select the relevant metrics and add them to the **Selected metrics** list.

   - If you are defining metrics for a host group, define the aggregation method. Datadog applies the selected method to the metrics from all hosts.

   Click **OK**.

   The measurements are displayed in the **Resource Measurements** pane of the Datadog dialog box.

```

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +For metrics that are collected from multiple hosts (as indicated in the **Machine** column), each data point in the graph gives the aggregated value for all hosts. The aggregation method is indicated
```suggestion
For metrics that are collected from multiple hosts (as indicated in the **Machine** column), each data point in the graph gives the aggregated value for all hosts. The aggregation method is indicated in the metric name, for example, `avg:metric1`.

```

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +When a metric is showing aggregated results from more than one host, the names of all hosts are included in the **Measurement** column in the legend. The aggregation method is indicated in the metric
```suggestion
When a metric is showing aggregated results from more than one host, the names of all hosts are included in the **Measurement** column in the legend. The aggregation method is indicated in the metric name, for example, `avg:metric1`.

```

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +Click **Connect**.
```suggestion
   ![snapshot][2]

   -  **Site**. Select the Datadog site where you have your user account.

   -  **API key and application key**. These are generated in Datadog for your user account.

   Click **Connect**.

```

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +### To set up the Datadog monitor:
```suggestion
### LoadRunner Professional Datadog monitor

```

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +4. Define the following to set up the connection to the Datadog server:
```suggestion
4. Define the following to set up the connection to Datadog:

```

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +## Datadog graph
```suggestion
## Analysis Datadog graph

```

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +**Note:** If you select more than one host, this creates a host group for the metrics.
```suggestion
   Select the host or hosts from which you want to pull metrics, and click **OK**.

   ![snapshot][3]

   **Note:** If you select more than one host, this creates a host group for the metrics.

```

2022-11-16 22:50 UTC, buraizu commented on loadrunner/README.md
> +1. In Controller, on the **Run** tab, select **Graphs > Datadog Graphs > Datadog**.
```suggestion
1. In the LoadRunner Controller, on the **Run** tab, select **Graphs > Datadog Graphs > Datadog**.

```

2022-11-17 15:41 UTC, emarsha94 requested changes
Hi team! Excited for the integration. As discussed in our call today, the integration will also need to send data into Datadog. I am adding a hold label on the PR until the integration is updated to send data to Datadog. Please let me know if you have any questions!

2022-12-07 15:19 UTC, closed without merging