Add homer Integration
DataDog/integrations-extras pull request #1610
Opened 2022-11-21 18:01 UTC by devopsec

### What does this PR do?

Adds integration for homer HEP server.

### Motivation

No integrations for this service existed.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

None.

2022-11-21 18:56 UTC, devopsec commented
fixed CI build integration

2022-11-23 18:58 UTC, buraizu requested changes

2022-11-24 10:24 UTC, FlorentClarret requested changes
Hi! Thanks for this PR. 

I've made a first pass. Let me know if you need any help 🙂

2022-11-24 10:24 UTC, FlorentClarret commented on homer/datadog_checks/homer/check.py
> +            return None
```suggestion
            return
```

Also you could log the message using `self.log.error`

2022-11-24 10:24 UTC, FlorentClarret commented on homer/datadog_checks/homer/check.py
> +                down_services.append(service)
Small nit, you could write this that way `down_services = [s for s in homer_service_checks if self.is_proc_alive(s)]`

2022-11-24 10:24 UTC, FlorentClarret commented on homer/datadog_checks/homer/check.py
> +            conn2.close()
Alternatively, you could remove `ConnNoop()` and close `conn1` and `conn2` if they are not None

2022-11-24 10:24 UTC, FlorentClarret commented on homer/datadog_checks/homer/check.py
> +            return None
```suggestion
            return
```

2022-11-24 10:24 UTC, FlorentClarret commented on homer/datadog_checks/homer/check.py
> +        return False
Does that mean that the agent has to run on the exact same host as your homer services?

2022-11-24 10:24 UTC, FlorentClarret commented on homer/images/IMAGES_README.md
> +```
You can remove this file

2022-11-24 10:24 UTC, FlorentClarret commented on homer/metadata.csv
> +homer.txcount.registration,gauge,,,,,0,homer,homer.txcount.registration,
Could you also provide a `description` to your metrics?

2022-11-24 10:24 UTC, FlorentClarret commented on homer/setup.py
> +        'Programming Language :: Python :: 2.7',
```suggestion
```

2022-11-24 10:24 UTC, FlorentClarret commented on homer/tests/test_homer.py
> +    aggregator.assert_metrics_using_metadata(get_metadata_metrics())
You can also assert the service checks

2022-11-24 10:24 UTC, FlorentClarret commented on homer/tox.ini
> +    pytest -v {posargs}
You do not need a tox because you are using hatch 🙂

2022-11-24 10:24 UTC, FlorentClarret commented on homer/manifest.json
> +  },
You should also add your dashboard in this section

2022-11-24 10:49 UTC, FlorentClarret commented on homer/manifest.json
> +  "display_on_public_website": false,
Is there a particular reason to set this to `false`?

2023-07-10 10:39 UTC, alopezz commented
@devopsec Do you still intend to work on this?

2023-08-21 09:08 UTC, alopezz commented
Closing this due to inactivity. Feel free to re-open if you start working on it again.

2023-08-21 09:08 UTC, closed without merging