Add Instabug Integration
DataDog/integrations-extras pull request #1613
Opened 2022-11-22 14:18 UTC by AbdallahHemdan

### What does this PR do?
Add integration for Instabug dashboard inside datadog

### Motivation
Allow Datadog users that already use Instabug to have a single source of truth of the data and be able to view the main insights from Instabug dashboard

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, the docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes
Nothing

2022-12-01 01:17 UTC, buraizu requested changes
Thank you for the PR, I've made some suggestions as outlined in our contributing guidelines:
https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md

Please let me know if you have any questions.

2022-12-01 01:17 UTC, buraizu commented on instabug/README.md
> +4. Search for Instabug to find the Instabug widget in the Apps section of the widget drawer.
```suggestion
4. Search for `Instabug` to find the Instabug widget in the Apps section of the widget drawer.
```

2022-12-01 01:17 UTC, buraizu commented on instabug/README.md
> +5. Click or drag the Instabug widget icon to add your dashboard and open the Instabug editor modal.
```suggestion
5. Click or drag the Instabug widget icon to add it to your dashboard and open the Instabug editor modal.
```

2022-12-01 01:17 UTC, buraizu commented on instabug/README.md
> +7. Optionally give the widget a title.
```suggestion
7. Optionally, give the widget a title.
```

2022-12-01 01:17 UTC, buraizu commented on instabug/README.md
> +8. Press Save to finish configuring the Datadog dashboard widget.
```suggestion
8. Press **Save** to finish configuring the Datadog dashboard widget.
```

2022-12-07 22:38 UTC, emarsha94 requested changes

2022-12-07 22:38 UTC, emarsha94 commented on instabug/manifest.json
> +  "display_on_public_website": false,
```suggestion
  "display_on_public_website": true,
```

2022-12-07 22:38 UTC, emarsha94 commented on instabug/manifest.json
> +    "media": [],
We highly recommend including images like dashboards, graphs, etc

2022-12-07 22:38 UTC, emarsha94 commented on instabug/manifest.json
> +      "Supported OS::Linux",
```suggestion
      "Offering::Integration",
      "Supported OS::Linux",
```

2022-12-07 22:38 UTC, emarsha94 commented on instabug/images/IMAGES_README.md
> +# Marketplace Media Carousel Guidelines
This file can be removed

2022-12-07 22:40 UTC, emarsha94 commented
Hi @AbdallahHemdan - excited for the integration. I left some comments on the PR along with our documentation team. Please let me know if you have questions! 

Additionally, can you please include a logo in .svg format? Thanks!

2022-12-11 11:31 UTC, AbdallahHemdan commented
@emarsha94 Thanks for your detailed review, I have applied all the review comments. Our team is working on the media part, I gonna update it once it becomes ready.

2022-12-12 18:17 UTC, buraizu approved these changes
Thank you for implementing those changes, and apologies -- I realize that my suggestions introduced some repetition into the leading paragraph.

This followup suggestion addresses that, but otherwise this looks good to me.

2022-12-12 18:17 UTC, buraizu commented on instabug/README.md
> +[Instabug][1] helps mobile teams proactively improve the quality of their mobile apps and deliver the high-quality experience to end users. You can use APM, Crash Reporting, and Bug Reporting tools t
```suggestion
[Instabug][1] helps mobile teams proactively improve the quality of their mobile apps and deliver a high-quality experience to end users. You can use APM, Crash Reporting, and Bug Reporting tools to help optimize your app's performance and improve the end-user experience.
```

2022-12-13 14:12 UTC, FlorentClarret reviewed
Hi! I left some minor comments. I'll review it again once the python files will be up to date!

2022-12-13 14:12 UTC, FlorentClarret commented on .github/CODEOWNERS
> +/instabug/                               @AbdallahHemdan ahemdan@instabug.com
Could you also add instabug in [this section](https://github.com/DataDog/integrations-extras/blob/master/.github/CODEOWNERS#L174) so our doc team gets notified when the README, metadata or manifest files are modified?

2022-12-13 14:12 UTC, FlorentClarret commented on instabug/datadog_checks/instabug/__about__.py
> +__version__ = '0.0.1'
```suggestion
__version__ = '1.0.0'
```

This will be the first released version 🙂

2022-12-19 21:21 UTC, emarsha94 requested changes

2022-12-19 21:21 UTC, emarsha94 commented on instabug/README.md
> +Need help? Contact [Datadog Support][3].
@AbdallahHemdan bumping this!

2022-12-19 21:21 UTC, emarsha94 commented on instabug/manifest.json
> +    "media": [],
Hi @AbdallahHemdan - saw you marked this as resolved. We highly recommend images be included in the offering. Are you able to include images here?

2023-01-07 23:52 UTC, AbdallahHemdan commented on instabug/README.md
> +Need help? Contact [Datadog Support][3].
@emarsha94 I can see that all the integrations on the master branch use `Datadog Support`, do we need to change that ?

2023-01-10 11:16 UTC, AbdallahHemdan commented
@FlorentClarret @emarsha94 We have added all the media files, could you please check again and let me know if there is anything missing?

2023-01-10 16:46 UTC, anawishnoff commented
Hi @AbdallahHemdan, our team emailed over a PDF with feedback on your app last month. Once that's addressed, we can continue to review and merge this PR. Thanks!

2023-01-10 19:23 UTC, AbdallahHemdan commented
@anawishnoff Thanks for your fast response, I think we are done with applying all the `required` comments you sent 👍🏻

2023-01-17 15:36 UTC, emarsha94 commented on instabug/README.md
> +Need help? Contact [Datadog Support][3].
Hi @AbdallahHemdan - yes, this will need to be changed to Instabug's support team email alias. Thanks!

2023-01-17 15:40 UTC, emarsha94 requested changes
Once the support emails are changed, we will just need to update the Changelog date to reflect the release date which I will request before we merge! Thanks!

2023-01-17 15:40 UTC, emarsha94 commented on instabug/manifest.json
> +    "support_email": "ahemdan@instabug.com",
This needs to be an email alias instead of a specific person. Thanks!

2023-01-18 04:54 UTC, AbdallahHemdan commented
@emarsha94 I have applied all the review comments, please check and let me know if you have any other comments 👍🏻 
Regarding updating the Changelog date to reflect the release date, I think we can do that after aligning the merge for the marketplace PR, once confirmed I will let you know about the release day 🙏🏻

2023-01-18 20:04 UTC, emarsha94 commented on .github/CODEOWNERS
> +/instabug/                               @AbdallahHemdan ahemdan@instabug.com
Please add @DataDog/marketplace-review to the codeowners file

2023-01-18 20:05 UTC, emarsha94 approved these changes
Two minor changes:
1. Add @DataDog/marketplace-review to the codeowners file
2. Changelog date

Thanks for all your hard work on this!

2023-01-18 20:05 UTC, emarsha94 commented on instabug/CHANGELOG.md
> +## 1.0.0 / 2022-11-22
```suggestion
## 1.0.0 / 2023-01-24
```

2023-01-24 16:52 UTC, eho1307 commented
Spoke over email but adding it here for visibility. This PR includes files needed for an agent based integration. Since this is an app, please close this PR and re-open a new one with the correct files.

2023-01-26 11:40 UTC, closed without merging