Update Hasura Cloud integration with traces
DataDog/integrations-extras pull request #1615
Opened 2022-11-23 19:43 UTC by sfarqu

### What does this PR do?

This PR adds documentation for the fact that Hasura Cloud integration now supports sending traces to DataDog

### Motivation

Tracing feature was added to our DataDog integration

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2022-11-23 22:19 UTC, cswatt requested changes

2022-11-23 22:19 UTC, cswatt commented on hasura_cloud/README.md
> +your Hasura Cloud project's operation logs, metrics and traces to your Datadog dashboard.
```suggestion
your Hasura Cloud project's operation logs, metrics, and traces to your Datadog dashboard. 
```

2022-11-23 22:19 UTC, cswatt commented on hasura_cloud/README.md
> +Logs, metrics and traces from your Hasura Cloud project will be automatically sent to Datadog when your project receives traffic.
```suggestion
Logs, metrics, and traces from your Hasura Cloud project are automatically sent to Datadog when your project receives traffic.
```

2022-11-24 11:57 UTC, FlorentClarret approved these changes

2022-11-24 23:49 UTC, sfarqu commented on hasura_cloud/README.md
> +Logs, metrics and traces from your Hasura Cloud project will be automatically sent to Datadog when your project receives traffic.
Suggested changes made.

2022-11-29 22:07 UTC, maycmlee approved these changes

2022-11-30 07:58 UTC, merged