go_pprof_scraper: fix typos and inconsistencies in docs
DataDog/integrations-extras pull request #1627
Opened 2022-12-08 14:52 UTC by nsrip-dd

### What does this PR do?

Fixes a typo and an inconsistency in the `go_pprof_scraper` integration docs.

### Motivation

README.md had the wrong name for the integration, and the configuration docs
incorrectly described the behavior of the "cumulative" parameter.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

2022-12-08 22:03 UTC, jtappa requested changes

2022-12-08 22:03 UTC, jtappa commented on go_pprof_scraper/assets/configuration/spec.yaml
> +        "cumulative" to true.
```suggestion
        For the heap profile, the in-use (also known as "live heap") samples
        may be negative if "cumulative" is false. This does not
        display accurately in the profile UI, so Datadog does not
        recommend setting "cumulative" to true.
```

2022-12-08 22:03 UTC, jtappa commented on go_pprof_scraper/datadog_checks/go_pprof_scraper/data/conf.yaml.example
> +    ## "cumulative" to true.
```suggestion
    ## For the heap profile, the in-use (also known as "live heap") samples
    ## may be negative if "cumulative" is false. This does not
    ## display accurately in the profile UI, so Datadog does not
    ## recommend setting "cumulative" to true.
```

2022-12-12 17:13 UTC, jtappa approved these changes

2022-12-13 14:32 UTC, FlorentClarret approved these changes

2022-12-13 14:56 UTC, merged