Update Flagsmith integration instructions
DataDog/integrations-extras pull request #1751
Opened 2023-02-03 18:50 UTC by dabeeeenster

### What does this PR do?

Updates the Flagsmith installation instructions to correct them.

### Motivation

A fix was needed!

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

N/A

2023-02-03 21:07 UTC, jtappa requested changes

2023-02-03 21:07 UTC, jtappa commented on flagsmith/README.md
> +In the [Flagsmith Dashboard](https://app.flagsmith.com/), select the Integrations Menu and then add the Datadog Integration. Enter your [Datadog API Key][2]. For Base URL, enter `https://api.datadogh
```suggestion
In the [Flagsmith Dashboard][2], select the Integrations Menu and then add the Datadog Integration. Enter your [Datadog API Key][3]. For Base URL, enter `https://api.datadoghq.com` if you are using the US Datadog site, or `https://api.datadoghq.eu` if you are using the EU Datadog site.
```

2023-02-03 21:07 UTC, jtappa commented on flagsmith/README.md
> +[4]: https://docs.datadoghq.com/help/
```suggestion
[2]: https://app.flagsmith.com/
[3]: https://app.datadoghq.com/organization-settings/api-keys
[4]: https://docs.flagsmith.com/integrations/datadog/
[5]: https://docs.datadoghq.com/help/
```

2023-02-03 21:07 UTC, jtappa commented on flagsmith/README.md
> +Need help? See the [Flagsmith documentation][3] or contact [Datadog Support][4].
```suggestion
Need help? See the [Flagsmith documentation][4] or contact [Datadog Support][5].
```

2023-02-06 12:08 UTC, dabeeeenster commented
OK thanks all suggestions committed!

2023-02-06 18:00 UTC, jtappa approved these changes

2023-02-06 22:06 UTC, merged