Initial Resmo Integration
DataDog/integrations-extras pull request #1780
Opened 2023-03-07 12:53 UTC by shuetisha

### What does this PR do?

Adds an Resmo integration to Datadog

### Motivation

The [Resmo][https://resmo.com] is a continuous asset visibility, security, and compliance solution for cloud and SaaS. Integrate with your tools to start querying and securing your resources. Monitor them in one place, run security and compliance audits, and get alerted on violations.
Using our APIs, engineers are free to focus on building core functionality, rather than having to provision and maintain servers and cloud infrastructure.

What does Resmo offer to Datadog users?
- Collect and monitor all your Datadog assets on a single platform.
- Query your Datadog monitors, roles, permissions, API Keys, and more.
- Set up rules to continuously assess your Datadog resources.
- Set up and receive rule notifications based on your Datadog resource configurations.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2023-03-07 16:25 UTC, maycmlee commented
Created [DOCS-5013](https://datadoghq.atlassian.net/browse/DOCS-5013) for docs review.

2023-03-10 01:54 UTC, buraizu requested changes
Thanks for the pull request, and nice work on the documentation!
I left some minor suggestions based on our style guide:
https://github.com/DataDog/documentation/blob/master/CONTRIBUTING.md
Please let me know if you have any questions.

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +[11]: https://docs.datadoghq.com/help/
```suggestion
[11]: https://docs.datadoghq.com/help/
[12]: https://docs.datadoghq.com/account_management/api-app-keys/#add-an-api-key-or-client-token
[13]: https://docs.datadoghq.com/account_management/api-app-keys/#add-application-keys
```

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +- Then, go to your Datadog account and create a new organization API key and a user Application key.<br />
As the instructions for creating these resources already exist at the new links added here, there's no need to duplicate them in this document.

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +- Return to your Resmo account. Enter the copied keys into the related key fields (Organization API Key and User App Key). <br />
```suggestion
4. Return to your Resmo account and enter the copied keys into the Organization API Key and User App Key fields. <br />
```

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +-Hit the create button, and that's it! You're ready to query your Datadog resources.
```suggestion
6. Click the **create** button, and you're ready to query your Datadog resources.
```

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +- **In Resmo**: Go to Settings>Integrations and select the Datadog integration you wish to uninstall. <br />
```suggestion
- **In Resmo**: Go to Settings>Integrations and select the Datadog integration you wish to uninstall. <br />
```
```suggestion
- **In Resmo**: Go to **Settings > Integrations** and select the Datadog integration you wish to uninstall. <br />
```

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +  - To permanently remove the integration, click the Delete button.
```suggestion
  - To temporarily pause the integration, click the **Disable** button.
  - To permanently remove the integration, click the **Delete** button.
```

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +See [Resmo Datadog Resources][9] for the list of resources we collect from your Datadog account.
```suggestion
See [Resmo Datadog Resources][9] for the list of resources collected from your Datadog account.
```

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +Need help? Contact [Resmo support][10] or [Datadog support][11]
```suggestion
Need help? Contact [Resmo support][10] or [Datadog support][11].
```

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +- Write a descriptive name and optionally a description.
```suggestion
2. Click **Add Integration** and select **Datadog**. Write a descriptive name and optionally a description.<br />
```

2023-03-10 01:54 UTC, buraizu commented on resmo/README.md
> +- Select a site from the dropdown menu on the last field.
```suggestion
5. Select a site from the dropdown menu on the last field.
```

2023-03-14 16:48 UTC, buraizu requested changes
Thank you for applying that feedback. I've left some additional feedback and some optional suggestions. 
Also, it looks like a check is failing due to images not being checked into the repo under the `resmo/images` folder. Would you be able to include the images?
Thanks again, and let me know if you have any questions.

2023-03-14 16:48 UTC, buraizu commented on resmo/README.md
> +
```suggestion
## Data Collected

See [Resmo Datadog Resources][9] for the list of resources collected from your Datadog account.

```

2023-03-14 16:48 UTC, buraizu commented on resmo/README.md
> +
Optional suggestion to move the **Data Collected** section above **Uninstallation** -- I think that users will want to see the value of the integration after it's installed, and then learn how to uninstall if needed -- but that's just my opinion, so feel free to ignore this suggestion if this format is intentional for some other reason.

2023-03-14 16:48 UTC, buraizu commented on resmo/README.md
> +See [Resmo Datadog Resources][9] for the list of resources collected from your Datadog account.
```suggestion
```

2023-03-14 16:48 UTC, buraizu commented on resmo/README.md
> +See [Resmo Datadog Resources][9] for the list of resources collected from your Datadog account.
As mentioned above, this is an optional suggestion to move this section.

2023-03-14 16:48 UTC, buraizu commented on resmo/README.md
> +  - To permanently remove the integration, click the **Delete** button.
```suggestion
  1. To temporarily pause the integration, click the **Disable** button.
  2. To permanently remove the integration, click the **Delete** button.
```

2023-03-14 16:48 UTC, buraizu commented on resmo/README.md
> +- You have two options;
```suggestion
- You have two options:
```

2023-03-15 09:12 UTC, closed without merging