Added Flagsmith datadog widget
DataDog/integrations-extras pull request #1793
Opened 2023-03-23 14:14 UTC by dabeeeenster

### What does this PR do?

Adds the Flagsmith dashboard widget to our Flagsmith integration tile.

### Motivation

We've had the Flagsmith widget approved and want to communicate it.

### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [X] Feature or bugfix has tests
- [X] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Nothing!

2023-03-23 21:34 UTC, rtrieu requested changes
Some minor suggestions, but otherwise looks good.

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. Make sure you are logged into Flagsmith with the account you want to see in Datadog.
```suggestion
2. Make sure you are logged into Flagsmith with the account you want to see in Datadog.
```

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. In Datadog, navigate to an existing dashboard or create a new one.
```suggestion
3. In Datadog, navigate to an existing dashboard or create a new one.
```

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. Press the **Add Widgets** button to expose the widget drawer.
```suggestion
4. Press the **Add Widgets** button to expose the widget drawer.
```

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. Search for **Flagsmith** to find the Flagsmith widget in the **Apps** section of the widget drawer.
```suggestion
5. Search for **Flagsmith** to find the Flagsmith widget in the **Apps** section of the widget drawer.
```

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. Select the **Flagsmith widget icon** to add it your your dashboard and open the **Flagsmith editor** modal. You can choose to add either the Flag or Audit log viewer widget.
```suggestion
6. Select the **Flagsmith widget icon** to add it your your dashboard and open the **Flagsmith editor** modal. You can choose to add either the Flag or Audit log viewer widget.
```

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. Select the Flagsmith Organisation, Project and Environment you want to add to your dashboard.
```suggestion
7. Select the Flagsmith Organization, Project and Environment you want to add to your dashboard.
```

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. Once selected, copy and paste the **Project ID** and **Environment ID** into Datadog.
```suggestion
8. Once selected, copy and paste the **Project ID** and **Environment ID** into Datadog.
```

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. Select the page size and, optionally, a widget title and Flagsmith Tag to filter on.
```suggestion
9. Select the page size and, optionally, a widget title and Flagsmith Tag to filter on.
```

2023-03-23 21:34 UTC, rtrieu commented on flagsmith/README.md
> +1. Click **Save** to finish configuring the dashboard widget.
```suggestion
10. Click **Save** to finish configuring the dashboard widget.
```

2023-03-23 22:59 UTC, dabeeeenster commented
OK thanks all these suggestions are committed

2023-03-23 23:06 UTC, rtrieu approved these changes
Hey @dabeeeenster sorry for not catching this before, but FYI I fixed and reordered the links, which should follow our [relative link convention](https://datadoghq.atlassian.net/wiki/spaces/docs4docs/pages/1182958054/Markdown#Links), otherwise they may break in production.

2023-03-30 18:08 UTC, emarsha94 approved these changes

2023-04-04 15:57 UTC, emarsha94 approved these changes

2023-04-20 19:41 UTC, merged