Fix Pihole Integration to support Pihole v5.x and Datadog Agent v7+
DataDog/integrations-extras pull request #1796
Opened 2023-03-29 20:03 UTC by troyfontaine

### What does this PR do?

This fixes the Pihole integration to support both Datadog Agent v7 and Pihole v5 (as the API requires an API token currently to be able to query metrics.

### Motivation

I was attempting to use this integration on my homelab and ran into a number of errors, starting from the attempt to query the API (bad URL), to the authentication required now and finished with the necessity to pass the metrics as floating point numbers instead of the string they originally were configured to use.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2023-03-29 21:42 UTC, hestonhoffman approved these changes
A couple of small docs edits, but this is good to go from the docs perspective. Thanks for the contribution!

2023-03-29 21:42 UTC, hestonhoffman commented on pihole/README.md
> +2. Edit the `conf.d/pihole.d/conf.yaml` by adding an instance and including both the host and API token in order to start collecting your Pi-hole metrics. See the [sample pihole.d/conf.yaml][7] for a
```suggestion
1. In the root of your Agent's configuration directory, copy `conf.d/pihole.d/conf.yaml.example` to `conf.d/pihole.d/conf.yaml`.
2. Edit `conf.d/pihole.d/conf.yaml` by adding an instance and including both the host and API token in order to start collecting your Pi-hole metrics. See the [sample pihole.d/conf.yaml][7] for all available configuration options.
```

2023-03-29 22:00 UTC, troyfontaine commented
> A couple of small docs edits, but this is good to go from the docs perspective. Thanks for the contribution!

Thanks!

2023-04-03 15:37 UTC, troyfontaine commented
I'm having some difficulty with fixing the tests-I've added in some logic to handle the difference between the numbers in the test and those actually being seen in API response from my PiHole instance-but getting the good_response to match up isn't working so well as I'm not very familiar with the test library and how to get the mock up to match up to the expected response properly.

2023-04-04 10:42 UTC, monganai commented
👋  Hey @troyfontaine

Thanks for your contributions here!

On my side, I have the integration running with Agent v7.4x.x  and i'm not using a token (I don't think it required one on initial setup)  In this case, the `token` should be optional rather than required for a given instance of the check.

In terms of testing the integration, the existing test instances target the output of hitting the different endpoints in [this repo](https://github.com/monganai/fake-hole/blob/master/fake-hole.py).   The [test suite](https://github.com/DataDog/integrations-extras/tree/master/pihole/tests) currently spins up the `fake-hole`  Docker container to test against, however I don't think it will handle being passed a token at this time.

Perhaps adding a new route in / updating `fake-hole.py`, to handle the addition of `?summary&auth=token` would be the most straight forward solution?  What are your thoughts?

2023-04-10 04:49 UTC, troyfontaine commented
> 👋 Hey @troyfontaine
> 
> Thanks for your contributions here!
> 
> On my side, I have the integration running with Agent v7.4x.x and i'm not using a token (I don't think it required one on initial setup) In this case, the `token` should be optional rather than required for a given instance of the check.
> 
> In terms of testing the integration, the existing test instances target the output of hitting the different endpoints in [this repo](https://github.com/monganai/fake-hole/blob/master/fake-hole.py). The [test suite](https://github.com/DataDog/integrations-extras/tree/master/pihole/tests) currently spins up the `fake-hole` Docker container to test against, however I don't think it will handle being passed a token at this time.
> 
> Perhaps adding a new route in / updating `fake-hole.py`, to handle the addition of `?summary&auth=token` would be the most straight forward solution? What are your thoughts?

I'll get on it!  Thanks!

2023-04-10 05:56 UTC, troyfontaine commented
@monganai I've made the token completely optional-if it is detected, it will use it, otherwise the integration will just keep trucking along.  I'll try and find some time next week to add the token route to the test container.  It looks like because I use a password on my pihole instances, the [token is required](https://pi-hole.net/blog/2022/11/17/upcoming-changes-authentication-for-more-api-endpoints-required/#page-content).  I can include this information in the readme as part of this PR or as a new PR if preferred.  Cheers!

2024-07-25 08:27 UTC, iliakur requested changes
Note that in order to release this you also need to bump the version number in `__about__.py`.

2024-07-25 08:27 UTC, iliakur commented on pihole/CHANGELOG.md
> +## [3.14.2] - 2023-03-29
```suggestion
## 3.14.2 - 2023-03-29
```

2024-07-25 08:27 UTC, iliakur commented on pihole/CHANGELOG.md
> +## [3.14.1] - Original Release
```suggestion
## 3.14.1 - Original Release
```

2025-04-10 21:26 UTC, closed without merging