RUMM-3242 add Roku integration tile
DataDog/integrations-extras pull request #1840
Opened 2023-05-03 13:14 UTC by xgouchet

### What does this PR do?

Adds Datadog RUM integration tile for Roku apps.

### Motivation

Surfacing the existing Roku RUM integration

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2023-05-03 13:27 UTC, fuzzybinary commented on rum_roku/README.md
> +# Android Integration
```suggestion
# Roku Integration
```

2023-05-03 13:28 UTC, fuzzybinary requested changes

2023-05-03 13:28 UTC, fuzzybinary commented on rum_roku/README.md
> +The AnRokudroid integration does not include any service checks.
```suggestion
The Roku integration does not include any service checks.
```

2023-05-03 19:45 UTC, alai97 approved these changes
Copy looks fantastic, thanks!

2023-05-11 18:15 UTC, alai97 commented on rum_roku/manifest.json
> +      "Supported OS::Roku"
```suggestion
```

2023-05-11 18:21 UTC, alai97 commented on rum_roku/manifest.json
> +      "Category::Tracing",
```suggestion
      "Category::Tracing"
```

2023-05-11 18:38 UTC, ofek approved these changes

2023-05-12 13:37 UTC, fuzzybinary approved these changes

2023-05-12 13:40 UTC, merged