Updating readme to include guide on integrating with docker agent
DataDog/integrations-extras pull request #1842
Opened 2023-05-04 15:44 UTC by chenbishop

### What does this PR do?

Adding steps for integrating with docker agent

### Motivation

User feature request.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2023-05-04 18:16 UTC, drichards-87 commented
Created DOCS-5432 for the Docs team review.

2023-05-08 14:43 UTC, estherk15 reviewed
Hi @chenbishop thanks for contributing to the our docs. Left a few notes on your requested changes, please let me know if you have any questions!

2023-05-09 11:21 UTC, chenbishop commented
@estherk15 thank you very much for your feedback, i have made all the recommended changes.

2023-05-09 14:54 UTC, estherk15 requested changes
Hi @chenbishop thanks for making those changes! A few more formatting changes and cleanup for the extra links. Please let me know if you have any questions!

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +##### (Host Agent) Set up Datadog Docker integration
```suggestion
##### Set up Datadog Docker integration for the Host Agent
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +- Adding the following lines to `datadog.yaml`:
```suggestion
Add the following lines to the `datadog.yaml` configuration file:
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +```
```suggestion
```yaml
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +##### (Container Agent) Set up Datadog Docker integration
```suggestion
##### Set up Datadog Docker integration for the Container Agent
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +- Add the `dd-agent` user to the `docker` group by using `usermod -a -G docker dd-agent`
```suggestion
- Add the `dd-agent` user to the `docker` group by using `usermod -a -G docker dd-agent`.
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +- Restart the Datadog Agent by running `service datadog-agent restart`
```suggestion
- Restart the Datadog Agent by running `service datadog-agent restart`.
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +4. Restart the Datadog Agent by running `service datadog-agent restart`
```suggestion
4. Restart the Datadog Agent by running `service datadog-agent restart`.
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +5. Confirm that the Twingate Analytic log appears in the [Log Explorer][10]
```suggestion
5. Confirm that the Twingate Analytic log appears in the [Log Explorer][10].
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +```
```suggestion
```shell
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +Adding additional label `com.datadoghq.ad.logs` to the Twingate Connector docker run command:
```suggestion
Add the label `com.datadoghq.ad.logs` to the Twingate Connector docker run command:
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +```
```suggestion
```shell
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +Note: The Twingate Connector container needs to be recreated to add the additional label
```suggestion
**Note**: The Twingate Connector container needs to be recreated to add the new label 
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +[16]: https://gist.github.com/chenbishop/3f1b9833f274716949a40af385e2f5c2
```suggestion
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +[17]: https://gist.github.com/chenbishop/7df60e074e7e856e17d867b31f6e95a1
```suggestion
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +[18]: https://gist.github.com/chenbishop/3be2bcc90d7d77288a843de469f0b3d0
```suggestion
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
> +[19]: https://gist.github.com/chenbishop/a5405cc00bc1ac50fdbd86ef4ad23599
```suggestion
```

2023-05-09 14:54 UTC, estherk15 commented on twingate/README.md
>     ```
```suggestion
   ```yaml
```

2023-05-09 14:54 UTC, estherk15 requested changes
Hi @chenbishop thanks for making those changes! A few more formatting changes and cleanup for the extra links. Please let me know if you have any questions!

2023-05-09 15:10 UTC, chenbishop commented
@estherk15 thank you very much for suggested changes, i have committed all the suggested changes.

2023-05-23 13:43 UTC, mgarabed approved these changes

2023-05-23 13:48 UTC, merged