Add DevCycle Integration Tile
DataDog/integrations-extras pull request #1849
Opened 2023-05-16 19:00 UTC by nikolasleblanc

### What does this PR do?

This PR creates a DevCycle tile and associated metadata to be displayed on the DataDog integrations page.

### Motivation

This PR relates to [this PR](https://github.com/DataDog/documentation/pull/17953), in which docs where added to the DataDog RUM Feature Flag Integration docs to describe how to track DevCycle variable evaluations.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Not sure if I nailed the metadata properly so happy to take edits if required.

2023-05-17 01:14 UTC, buraizu commented
Created DOCS-5501 to track.

2023-05-17 16:03 UTC, nikolasleblanc commented
@buraizu @rtrieu what should I use as the codeowners entry? It looks like it needs write access to this repo but I don't imagine you're handing that out to just anybody.

2023-05-24 18:43 UTC, rtrieu commented
@meghanlo Can you confirm that @nikolasleblanc added the information to the CODEOWNERS file in this repo correctly? Thank you!

2023-05-26 21:10 UTC, rtrieu requested changes
A few minor suggestions, but otherwise looks good!

2023-05-26 21:10 UTC, rtrieu commented on devcycle/README.md
> +DevCycle's feature flag tracking integration enriches your RUM data with your feature's variable evaluations to provide visibility into performance monitoring and behavioral changes. Determine which
```suggestion
DevCycle's feature flag tracking integration enriches your RUM data with your feature's variable evaluations to provide visibility into performance monitoring and behavioral changes. Determine which users are shown a specific user experience and if it is negatively affecting the user's performance.
```

2023-05-26 21:10 UTC, rtrieu commented on devcycle/README.md
> +Feature flag tracking is available in the RUM Browser SDK. For detailed set up instructions, visit the [Getting started with Feature Flag data in RUM][4] guide.
```suggestion
Feature flag tracking is available in the RUM Browser SDK. For detailed setup instructions, visit the [Getting started with Feature Flag data in RUM][4] guide.
```

2023-05-26 21:10 UTC, rtrieu commented on devcycle/images/IMAGES_README.md
> +can be a video (guidelines and submission steps below). Images should be
```suggestion
can be a video (see guidelines and submission steps below). Images should be
```

2023-05-26 21:10 UTC, rtrieu commented on devcycle/images/IMAGES_README.md
> +vimeo_id to add to your manifest.json file.  Please note that the gallery can
```suggestion
Vimeo ID to add to your `manifest.json` file.  Please note that the gallery can
```

2023-05-29 12:48 UTC, nikolasleblanc commented
Thanks @rtrieu, suggestions submitted!

2023-05-30 15:14 UTC, rtrieu approved these changes
lgtm

2023-05-30 17:47 UTC, nikolasleblanc commented
Thanks @rtrieu, @emarsha94 anything I can do about that CODEOWNERS file?

2023-05-31 15:04 UTC, yzhan289 requested changes
Just 1 small fix!

2023-05-31 18:47 UTC, nikolasleblanc commented on .github/CODEOWNERS
> +/devcycle                                @nikolasleblanc
Gah! There it is! Thanks!!

2023-06-02 14:27 UTC, nikolasleblanc commented
Hey @yzhan289 anything more I can do for this PR?

2023-06-02 15:34 UTC, yzhan289 approved these changes
Hi @nikolasleblanc, this PR LGTM, but before the tile will show up on the list of integrations, we need to sync this internally which will take some time (~ less than 2 weeks).

2023-06-02 15:35 UTC, yzhan289 commented
Hm it doesn't look like I can merge this PR since it has some merge conflicts. Can you resolve them and then ping me again?

2023-06-02 16:47 UTC, nikolasleblanc commented
@yzhan289 fixed!

2023-06-05 15:02 UTC, nikolasleblanc commented
Hey @yzhan289 - friendly ping!

2023-06-05 21:14 UTC, yzhan289 approved these changes
LGTM!

2023-06-05 21:14 UTC, merged

2023-06-06 20:28 UTC, nikolasleblanc commented
Hey @yzhan289 and @rtrieu one of my colleagues noticed typos in our code sample so I submitted a very small correction here: https://github.com/DataDog/integrations-extras/pull/1869