Mezmo
DataDog/integrations-extras pull request #1878
Opened 2023-06-11 19:29 UTC by lstott

First version of the Mezmo integration.

### What does this PR do?

Creates the initial (V1) Mezmo integration

### Motivation

To list the Mezmo integration.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2023-06-12 20:00 UTC, emarsha94 requested changes
Hi team! Thanks for submitting your PR. It looks like there is a duplication of all files in this PR. Can you remove all the duplicates or submit a PR with the just the files needed? Thanks!

2023-06-12 20:00 UTC, emarsha94 commented on amixr/mezmo/README.md
> +Mezmo Telemetry Pipeline empowers teams to ingest, transform, and route telemetry data in real-time. You can ingest telemetry data from various sources via our open platform, apply transformation and
The overview section should include the following:

1. What does Mezmo do in 1-2 sentences?
2. What will customers get from this integration?
3. What types of data does this send in and the value of the data?

2023-06-12 20:00 UTC, emarsha94 commented on amixr/mezmo/assets/dashboards/mezmo_telemetry_pipeline_overview.json
Please include a dashboard with your integration

2023-06-12 20:00 UTC, emarsha94 commented on amixr/mezmo/images/IMAGES_README.md
This can be deleted

2023-06-12 20:00 UTC, emarsha94 commented on amixr/mezmo/manifest.json
> +  "manifest_version": "1.0.0",
```suggestion
  "manifest_version": "2.0.0",
```

2023-06-12 21:37 UTC, cswatt commented
Created ticket for docs team to review readme.

2023-06-16 15:19 UTC, emarsha94 requested changes

2023-06-16 15:19 UTC, emarsha94 commented on mezmo/README.md
> +Mezmo Telemetry Pipeline empowers teams to ingest, transform, and route telemetry data in real-time. You can ingest telemetry data from various sources via our open platform, apply transformation and
The overview section should include the following:

What does Mezmo do in 1-2 sentences?
What will customers get from this integration?
What types of data does this send in and the value of the data?

2023-06-16 15:19 UTC, emarsha94 commented on mezmo/assets/dashboards/mezmo_telemetry_pipeline_overview.json
Please include a dashboard

2023-06-16 15:19 UTC, emarsha94 commented on mezmo/images/IMAGES_README.md
Please remove this file

2023-06-16 15:19 UTC, emarsha94 commented on mezmo/manifest.json
> +  "display_on_public_website": false,
```suggestion
  "display_on_public_website": true,
```

2023-06-20 19:18 UTC, aliciascott commented
Hi @lstott thank you for this contribution! Can you review and make the suggested changes from @emarsha94 and then we can move forward with the editorial review. Thanks!

2023-06-21 21:35 UTC, lstott commented on mezmo/assets/dashboards/mezmo_telemetry_pipeline_overview.json
Hi, do you have any sample dashboards I can base this off of? Not a DD user so any help is appreciated.

2023-06-21 21:36 UTC, lstott commented on mezmo/assets/logos/Mezmo_Logo_Charged-Yellow-Grounded-Green_RGB_Square.svg
Is it due to the size? if you download the logo you can see it's not a black square.

2023-06-30 15:04 UTC, anawishnoff commented on amixr/mezmo/assets/dashboards/mezmo_telemetry_pipeline_overview.json
Hi @lstott, you can view our dashboarding best practices here which was examples and guidelines: https://datadoghq.dev/integrations-core/guidelines/dashboards/#best-practices

2023-06-30 15:04 UTC, anawishnoff commented on mezmo/assets/logos/Mezmo_Logo_Charged-Yellow-Grounded-Green_RGB_Square.svg
This looks fine now

2023-06-30 15:05 UTC, anawishnoff commented
Hi @lstott, once the comments from @emarsha94 are addressed, we can do another round of reviews. Please feel free to ask any questions you may have on the requested changes. Thanks!

2023-07-06 18:48 UTC, lstott commented
Hi Ana,

Since we are a Pipeline company (meaning we help transport and transform
data) and we do not have any unique data of our own, I'm struggling to come
up with a unique Mezmo Datadog dashboard. Is this a hard requirement or can
there be an exception made given the nature of the Mezmo pipeline?

On Fri, Jun 30, 2023 at 9:05 AM Ana Wishnoff ***@***.***>
wrote:

> Hi @lstott <https://github.com/lstott>, once the comments from @emarsha94
> <https://github.com/emarsha94> are addressed, we can do another round of
> reviews. Please feel free to ask any questions you may have on the
> requested changes. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DataDog/integrations-extras/pull/1878#issuecomment-1614788709>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABSBD4ZSDV5KLSBTX2DNMHDXN3TLJANCNFSM6AAAAAAZCQVRZE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-06 19:12 UTC, anawishnoff commented
Hi @lstott, since you are sending metrics into Datadog as a part of this integration, we require an out of the box dashboard. It can be a simple dashboard, but should display the metrics that you're sending in, organized in a way that would make sense for customers.

The dashboard should also have your logo on it, and provide a description wtih links to any relevant documentation. Let me know if you have remaining concerns here. Thanks!

2023-07-06 19:15 UTC, lstott commented
The metrics can be anything that our mutual customers decide to send in. I
don't have a list of metrics that will be sent every time that I could use
in an OOB dashboard. Does that make sense?

On Thu, Jul 6, 2023 at 1:12 PM Ana Wishnoff ***@***.***>
wrote:

> Hi @lstott <https://github.com/lstott>, since you are sending metrics
> into Datadog as a part of this integration, we require an out of the box
> dashboard. It can be a simple dashboard, but should display the metrics
> that you're sending in, organized in a way that would make sense for
> customers.
>
> The dashboard should also have your logo on it, and provide a description
> wtih links to any relevant documentation. Let me know if you have remaining
> concerns here. Thanks!
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DataDog/integrations-extras/pull/1878#issuecomment-1624186020>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABSBD463G3OHCPAFKEG3ZPDXO4EY5ANCNFSM6AAAAAAZCQVRZE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-17 19:53 UTC, anawishnoff commented
Hi @lstott, as discussed over email and the recent call, this integration will need to send in specific metrics/logs/other data about the health of the Mezmo observability pipelines/other parts of your platform. An out of the box dashboard is also required to display all of that data in one place. 

Please let us know if you have any questions, thank you!

2023-11-06 21:49 UTC, emarsha94 commented
@lstott As discussed via email, we will go ahead and close this out until the integration has been completed. Feel free to re-open once you integration is completed and ready for review!

2023-11-06 21:49 UTC, closed without merging