Added hikaricp.connections.max (pool max size)
DataDog/integrations-extras pull request #1890
Opened 2023-06-19 01:35 UTC by styner9

### What does this PR do?
Add `hikaricp.connections.max` for HikariCP max connection pool size.

### Motivation
I wnat to calculate a pool utilization. To do so, I need to know the maximum size and the number of idle/busy connections.
But, max size is not provided.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes
N/A

2023-06-19 16:33 UTC, kayayarai requested changes

2023-06-19 16:33 UTC, kayayarai commented on hikaricp/metadata.csv
> +hikaricp.connections.max,gauge,,,,Number of max connections,0,hikaricp,max connection number,
```suggestion
hikaricp.connections.max,gauge,,,,Max number of connections,0,hikaricp,max connection number,
```
Maybe?

2023-06-20 01:05 UTC, styner9 commented on hikaricp/metadata.csv
> +hikaricp.connections.max,gauge,,,,Number of max connections,0,hikaricp,max connection number,
@kayayarai Thanks!

2023-06-20 13:53 UTC, kayayarai approved these changes

2023-06-22 01:20 UTC, styner9 commented
@kayayarai Hi! I can't merge this PR because I don't have write access. Can you merge it for me?

2023-06-22 06:20 UTC, FlorentClarret requested changes
Thanks for the PR! 

Just left one comment on the metadata file

2023-06-22 06:20 UTC, FlorentClarret commented on hikaricp/metadata.csv
> +hikaricp.connections.max,gauge,,,,Max number of connections,0,hikaricp,max connection number,
nit, we have a unit `connection`

```suggestion
hikaricp.connections.max,gauge,,connection,,Max number of connections,0,hikaricp,max connection number,
```

2023-06-22 07:06 UTC, styner9 commented on hikaricp/metadata.csv
> +hikaricp.connections.max,gauge,,,,Max number of connections,0,hikaricp,max connection number,
@FlorentClarret Thank you!

2023-06-22 07:37 UTC, FlorentClarret approved these changes
👍

2023-06-22 07:38 UTC, FlorentClarret commented
Pinging @bertaudamien as the maintainer of this integration

2023-06-27 09:32 UTC, styner9 commented
@bertaudamien Hi! Could you review/merge this PR? Thank you in advance.

2023-08-09 13:27 UTC, FlorentClarret commented
Merging. I'll release a new version right after

2023-08-09 13:28 UTC, merged