Update changelog header formatting
DataDog/integrations-extras pull request #2050
Opened 2023-07-12 15:40 UTC by swang392

Update changelog formatting so it standardized.

I am working on a validation script that checks for correct headers, spacing, syntax, etc. and these fixes standardize the integrations and allow them to pass.

2023-07-12 21:27 UTC, ofek requested changes

2023-07-12 21:27 UTC, ofek commented on filebeat/CHANGELOG.md
> +
```suggestion
```

2023-07-13 11:22 UTC, iliakur reviewed
I noticed that in the ints-core repo the recent formatting changes seem to have left trailing whitespace after the "added/changed/etc" headers. Could you please make sure that's not happening here and maybe also fix it in core too?

2023-07-14 14:39 UTC, ofek approved these changes

2023-07-14 14:42 UTC, merged