fix(mergify): raise timeout error rather than returning None
DataDog/integrations-extras pull request #2084
Opened 2023-08-23 14:13 UTC by jd

The current behaviour is to return None which triggers an error later in the
code:

[{"message": "'NoneType' object is not subscriptable", "traceback": "Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/base/checks/base.py", line 1142, in run
    self.check(instance)
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mergify/check.py", line 29, in check
    self.send_queues_metrics()
  File "/opt/datadog-agent/embedded/lib/python3.8/site-packages/datadog_checks/mergify/check.py", line 86, in send_queues_metrics
    for queue in response_json["queues"]:
TypeError: 'NoneType' object is not subscriptable
"}]

This implements the same behaviour than the other errors, being raising back
the error to the caller.

### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [X] Git history is clean
- [X] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

2023-08-25 08:36 UTC, jd commented
Any clue as to why the CI is failing?
There's no change locally:
```
$ ddev validate models -s mergify
Validating data models for 1 checks ...
mergify:
All 5 data model files are in sync!
```

2023-08-31 06:40 UTC, FlorentClarret commented
> Any clue as to why the CI is failing? There's no change locally:
> 
> ```
> $ ddev validate models -s mergify
> Validating data models for 1 checks ...
> mergify:
> All 5 data model files are in sync!
> ```

You'd need the latest version of ddev to update the config models. This is done [here](https://github.com/DataDog/integrations-extras/pull/2088).

Note that is this will required with Agent 7.48.0, so you can ignore this for now, sorry for the noise.

2023-08-31 06:44 UTC, FlorentClarret requested changes

2023-08-31 06:44 UTC, FlorentClarret commented on mergify/datadog_checks/mergify/config_models/__init__.py
> +# (C) Datadog, Inc. 2023-present
Could you revert all the changes to the files in the config_models folder? It is not needed right now, even if the CI fails atm. We'll fix that, sorry again for the noise

2023-08-31 07:13 UTC, FlorentClarret approved these changes

2023-09-08 14:38 UTC, merged