Adding 2 recommended monitors
DataDog/integrations-extras pull request #2140
Opened 2023-10-19 21:23 UTC by Dog-Gone-Earl

### What does this PR do?

Proposed addition of 2 recommended monitors for Fluxcd Integration.

### Motivation

https://datadoghq.atlassian.net/browse/AI-3001

### Review checklist

- [ X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ X] Feature or bugfix has tests
- [ X] Git history is clean
- [X ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Fluxcd sandbox running to simulate monitor behaviors.

Active Worker Count Monitor
https://dd.datad0g.com/monitors/11520271

![image](https://github.com/DataDog/integrations-extras/assets/107069502/42011d6c-0148-4cef-a152-75443a20a850)

Error Count Monitor
https://dd.datad0g.com/monitors/11520177

![image](https://github.com/DataDog/integrations-extras/assets/107069502/4e0bd536-c664-44b1-8b68-a6a70cba58f3)

Inclusion of `integration:fluxcd` tag links to OOTB dashboard.

2023-10-19 21:41 UTC, aliciascott approved these changes

2023-10-23 07:17 UTC, FlorentClarret approved these changes
Looks good to me! I just left one comment about a description and we're good to go!

2023-10-23 07:17 UTC, FlorentClarret commented on fluxcd/assets/recommended_monitors/error_count.json
> +      "description": "Notify your team when your active worker count has reached system resource capacity."
Could you update the description for this one? I think it's the same as the other one.

2023-10-23 07:17 UTC, FlorentClarret requested changes
See my comments

2023-10-23 17:48 UTC, Dog-Gone-Earl commented
Hi @FlorentClarret , thank you for that! Did not mean for that happen! I have updated to accurately reflect the `error count` monitor behavior.

![image](https://github.com/DataDog/integrations-extras/assets/107069502/0d4ee04b-355e-48dd-9d53-10471742d188)

2023-10-24 06:07 UTC, FlorentClarret approved these changes

2023-10-24 06:10 UTC, FlorentClarret commented
Thank you!

2023-10-24 06:10 UTC, merged