Add Akeyless Gateway Integration Tile
DataDog/integrations-extras pull request #2196
Opened 2023-11-21 13:46 UTC by akljph

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2023-11-28 16:04 UTC, emarsha94 requested changes

2023-11-28 20:24 UTC, akljph commented on akeyless_gateway/manifest.json
> +      "Supported OS::macOS"
Done :)

2023-11-29 23:50 UTC, alai97 commented on akeyless_gateway/metadata.csv
> +akeyless.gw.system.request_count,gauge,,,,Total number of requests,0,akeyless_gateway,,
```suggestion
akeyless.gw.system.cpu,gauge,,,,CPU utilization metrics.,0,akeyless_gateway,,
akeyless.gw.system.disk,gauge,,,,Disk I/O metrics.,0,akeyless_gateway,,
akeyless.gw.system.load,gauge,,,,CPU load metrics.,0,akeyless_gateway,,
akeyless.gw.system.memory,gauge,,,,Memory utilization metrics.,0,akeyless_gateway,,
akeyless.gw.system.network,gauge,,,,Network interface I/O metrics and TCP connection metrics.,0,akeyless_gateway,,
akeyless.gw.quota.current_transactions_number,gauge,,,,Current transaction number.,0,akeyless_gateway,,
akeyless.gw.quota.gw_admin_client_transactions,gauge,,,,Total transaction by an admin client.,0,akeyless_gateway,,
akeyless.gw.quota.total_transactions_limit,gauge,,,,Total transaction limit per hour.,0,akeyless_gateway,,
akeyless.gw.system.http_response_status_code,gauge,,,,Status of the HTTP response.,0,akeyless_gateway,,
akeyless.gw.system.request_count,gauge,,,,Total number of requests.,0,akeyless_gateway,,
```

2023-11-29 23:51 UTC, alai97 commented on akeyless_gateway/README.md
> +This integration allows you to visualize and monitor performance of your [Akeyless Gateway](https://docs.akeyless.io/docs/api-gw). Telemetry metrics are sourced from the application and the runtime e
```suggestion
This integration allows you to visualize and monitor performance of your [Akeyless Gateway][2]. Telemetry metrics are sourced from the application and the runtime environment.
```

2023-11-29 23:52 UTC, alai97 commented on akeyless_gateway/README.md
> +Akeyless offers a unique Gateway, which adds an extra level of protection between your private network and the cloud. Acting as a SaaS extension of our core services, our stateless Gateway enables a
```suggestion
Akeyless offers a unique Gateway which adds an extra level of protection between your private network and the cloud. Acting as a SaaS extension of our core services, our stateless Gateway enables a transparent internal operation with a robust out-of-the-box mechanism to ensure service continuity and recovery without having to change any network infrastructure in order to work with your internal resources.
```

2023-11-29 23:52 UTC, alai97 commented on akeyless_gateway/README.md
> +To configure the Akeyless Gateway integration on a [Gateway running on K8s](https://docs.akeyless.io/docs/gateway-k8s):
```suggestion
To configure the Akeyless Gateway integration on a [Gateway running on K8s][3]:
```

2023-11-29 23:52 UTC, alai97 commented on akeyless_gateway/README.md
> +1. In your `values.yaml` file you use to deploy your Gateway on Kubernetes, under the `metrics` section, add the below configuration. Set the relevant API Key of your Datadog server, and the relevant
```suggestion
1. In your `values.yaml` file you use to deploy your Gateway on Kubernetes, under the `metrics` section, add the following configuration. Set the relevant API Key of your Datadog server, and the relevant [Datadog site][1] such as: `app.datadoghq.com`.
```

2023-11-29 23:53 UTC, alai97 commented on akeyless_gateway/README.md
> +2. If you have not yet deployed the Gateway, continue with your installation as usual and run the following command when ready to deploy:
```suggestion
2. If you have not yet deployed the Gateway, continue with your installation as usual and run the following command when you are ready to deploy:
```

2023-11-29 23:53 UTC, alai97 commented on akeyless_gateway/README.md
> +To configure the Akeyless Gateway integration on a [Standalone Gateway](https://docs.akeyless.io/docs/install-and-configure-the-gateway):
```suggestion
To configure the Akeyless Gateway integration on a [Standalone Gateway][4]:
```

2023-11-29 23:54 UTC, alai97 commented on akeyless_gateway/README.md
> +1. Create a local file called `otel-config.yaml` with the below configuration. Set the relevant API Key of your Datadog server, and the relevant [Datadog site][1] (i.e. `app.datadoghq.com`).
```suggestion
1. Create a local file called `otel-config.yaml` with the following configuration. Set the relevant API Key of your Datadog server, and the relevant [Datadog site][1] such as `app.datadoghq.com`.
```

2023-11-29 23:54 UTC, alai97 commented on akeyless_gateway/README.md
> +2. If you have not yet deployed the Gateway, run the below command to spin up your Akeyless Gateway with the `ENABLE_METRICS=true` variable and mounting the `otel-config.yaml` file:
```suggestion
2. If you have not yet deployed the Gateway, run the following command to spin up your Akeyless Gateway with the `ENABLE_METRICS=true` variable and mount the `otel-config.yaml` file:
```

2023-11-29 23:56 UTC, alai97 commented on akeyless_gateway/README.md
> +Upon successful setup of the Gateway, go to the Metrics page on the Datadog platform, and filter the Akeyless metrics on the summary page.
What link should we include here, perhaps a dashboard link?
```suggestion
Upon successful setup of the Gateway, go to the [**Metrics** page][5] on the Datadog site, and filter the Akeyless metrics on the summary page.
```

2023-11-29 23:57 UTC, alai97 commented on akeyless_gateway/README.md
> +See [metadata.csv](/akeyless_gateway/metadata.csv) for a list of metrics provided by this integration.
```suggestion
See [metadata.csv][6] for a list of metrics provided by this integration.
```

2023-11-29 23:58 UTC, alai97 commented on akeyless_gateway/README.md
> +Akeyless Gateway does not include any service checks.
```suggestion
The Akeyless Gateway integration does not include any service checks.
```

2023-11-29 23:58 UTC, alai97 commented on akeyless_gateway/README.md
> +Akeyless Gateway does not include any events.
```suggestion
The Akeyless Gateway integration does not include any events.
```

2023-11-29 23:58 UTC, alai97 commented on akeyless_gateway/README.md
> +[1]: https://docs.datadoghq.com/getting_started/site/
Remember to replace [5] with a link to the "Metrics page on the Datadog Site that shows Akeyless metrics on the summary page".

```suggestion
[1]: https://docs.datadoghq.com/getting_started/site/
[2]: https://docs.akeyless.io/docs/api-gw
[3]: https://docs.akeyless.io/docs/gateway-k8s
[4]: https://docs.akeyless.io/docs/install-and-configure-the-gateway
[5]: TBD
[6]: https://github.com/DataDog/integrations-extras/blob/master/akeyless_gateway/metadata.csv
[7]: mailto:support@akeyless.io
```

2023-11-29 23:58 UTC, alai97 commented on akeyless_gateway/README.md
> +Need help? Contact [Akeyless Support](mailto:support@akeyless.io).
```suggestion
Need help? Contact [Akeyless Support][7].
```

2023-11-30 09:08 UTC, akljph commented
@alai97 

> Some suggestions + reminder to replace a link to a "Metrics page in Datadog"!

Should be all done :)

2023-12-04 16:18 UTC, emarsha94 approved these changes

2023-12-04 16:34 UTC, FlorentClarret approved these changes

2023-12-04 21:15 UTC, james-eichelbaum approved these changes

2023-12-07 18:32 UTC, merged