Add Vercel metrics metadata
DataDog/integrations-extras pull request #2215
Opened 2023-12-07 17:03 UTC by sfirrin

### What does this PR do?
Adding metadata for upcoming Vercel metrics

### Motivation
New Vercel metrics need metadata

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2023-12-07 17:11 UTC, Chronobreak approved these changes

2023-12-07 18:45 UTC, nathanmadams approved these changes

2024-01-03 13:26 UTC, FlorentClarret requested changes
Since we now have metrics, could you add one of them [here](https://github.com/DataDog/integrations-extras/blob/437611034b2a0c9cf1429852451bb262d7cdf23b/vercel/manifest.json#L42)? That's used to display `No data` in the UI. We typically specify a metric that we know is going to always be collected, I think `vercel.requests` is a good candidate in your case but I'll let you choose.

It will also fix the validation in the CI

2024-01-03 15:11 UTC, sfirrin commented
Hey @FlorentClarret yes that is the plan, I will update with a check metric. We initially were trying to see if we could get around the check requirement because this is being rolled out first to private beta orgs (and we don't want to show "no data" to orgs not in the beta) but found out this is not possible, so the metadata was updated manually for the time being. To avoid the false "no data" we are waiting to merge this until the metrics have been rolled out to all orgs

2024-01-03 15:26 UTC, FlorentClarret commented
> Hey @FlorentClarret yes that is the plan, I will update with a check metric. We initially were trying to see if we could get around the check requirement because this is being rolled out first to private beta orgs (and we don't want to show "no data" to orgs not in the beta) but found out this is not possible, so the metadata was updated manually for the time being. To avoid the false "no data" we are waiting to merge this until the metrics have been rolled out to all orgs

Sounds good to me! Feel free to ping me when this is ready to be merged!

2024-01-03 15:27 UTC, FlorentClarret approved these changes

2024-03-07 19:21 UTC, merged