Merge ping_identity into master
DataDog/integrations-extras pull request #2229
Opened 2023-12-13 22:46 UTC by ryan-schafer

### What does this PR do?

Creating a new tile listing for Ping Identity into Datadog marketplace.

### Motivation

We are working through partnership efforts and want to showcase the integration work done of the Datadog openAPI into the PingOne DaVinci product on your marketplace.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2023-12-13 22:50 UTC, ryan-schafer commented on ping_identity/manifest.json
> +    "homepage": "pingidentity.com",
homepage should read: https://www.pingidentity.com

Didn't know this would error.

2023-12-18 06:32 UTC, urseberry requested changes

2023-12-18 06:32 UTC, urseberry commented on ping_identity/README.md
> +Ping Identity delivers intelligent identity solutions for the enterprise. We enable companies to achieve Zero Trust identity-defined security and more personalized, streamlined user experiences.
```suggestion
Ping Identity delivers intelligent identity solutions for the enterprise. The Ping Identity platform enables companies to achieve Zero Trust identity-defined security and personalized, streamlined user experiences.
```

2023-12-18 06:32 UTC, urseberry commented on ping_identity/README.md
> +The Datadog API connector boasts over 350+ unique capabilites, each with a unique Datadag API endpoint to complete CRUD actions for many different Datadog components.
```suggestion
The Datadog API connector has over 350+ unique capabilities, each with a unique Datadog API endpoint to complete CRUD actions for many different Datadog components.
```

2023-12-18 06:32 UTC, urseberry commented on ping_identity/README.md
> +Installation with PingOne's DaVinci platform is simple and easy with Ping's drag and drop functionality on a flow canvas. Follow the below steps to configure Datadog within DaVinci:
```suggestion
Installation with PingOne's DaVinci platform uses Ping's drag and drop functionality on a flow canvas. Follow the below steps to configure Datadog within DaVinci:
```

2023-12-18 06:32 UTC, urseberry commented on ping_identity/README.md
> +1. On a flow, select the black "+" button in the bottom left corner of the flow canvas.
```suggestion
1. On a flow, select the black **+** button in the bottom left corner of the flow canvas. 
```

2023-12-18 06:32 UTC, urseberry commented on ping_identity/README.md
> +2. Search for Datadog and select it to add it to the canvas.
```suggestion
2. Search for "Datadog" and select it to add it to the canvas.
```
Can you replace "it" with a word that describes how "Datadog" appears? Is it a list item, a button, a tile, or something else?

2023-12-18 06:32 UTC, urseberry commented on ping_identity/README.md
> +3. Enter any additional information required for the connector to successfuly run. These will be capability dependent.
```suggestion
1. Click the connector to open the connector side panel. 
1. Select **Configure**.
1. Enter the API URL, API key, and application key from your Datadog tenant to configure the connector within your DaVinci tenant.
1. Click **Apply**.
1. Scroll and select the proper capability for your use case.
1. Enter any additional information required for the connector to successfully run. These are capability dependent.
```

2023-12-18 06:32 UTC, urseberry commented on ping_identity/README.md
> +You can validate that the connector is working by linking the connector to other connectors (namely the HTTP connector) to view the output of the connector in a demo flow. Utilize the "Custom HTML Me
```suggestion
You can validate that the connector is working by linking the connector to the HTTP connector to view the output of the connector in a demo flow:
1. Use the **Custom HTML Message** capability from the HTTP connector.
1. In the message field, select **{}** to choose the output from the Datadog connector.
1. Run the flow widget by selecting **Try Flow** in the upper right corner. The connector executes.
1.  <tell the user what to look for to determine if the connector is working correctly>
```

2023-12-18 06:32 UTC, urseberry commented on ping_identity/README.md
> +You can view general information on the DaVinci platform [here](https://docs.pingidentity.com/r/en-us/davinci/davinci_landing_page).
```suggestion
See [PingOne DaVinci](https://docs.pingidentity.com/r/en-us/davinci/davinci_landing_page) for general information on the DaVinci platform.
```

2023-12-18 06:32 UTC, urseberry commented on ping_identity/images/IMAGES_README.md
Please delete this file.

2023-12-18 22:57 UTC, eho1307 requested changes
Thank you for opening this PR! I've added comments inline. I'm also making a note that this PR will require an OAuth connection per Dominic's email. Feel free to address our changes now or you may wait until the OAuth changes are ready.

2023-12-18 22:57 UTC, eho1307 commented on ping_identity/README.md
> +Datadog integrates directly with the PingOne DaVinci platform through the Datadog API connector. PingOne DaVinci is an orchestration platform that lets you create flows using connections and logical
A few initial comments:

Do you have a more concrete example of what a user could build with DaVinci?
Can you also add more color into the kinds of actions users can perform with Datadog in DaVinci?

2023-12-18 22:57 UTC, eho1307 commented on ping_identity/images/datadogCapabilities.png
Please replace these with landscape images that fit our image requirements:
- The aspect ratio must be 16:9 exactly 
- Width: 1440px
- Minimum height: 810px
- Maximum height: 2560px

2023-12-18 22:57 UTC, eho1307 commented on ping_identity/images/datadogCapabilityConfig.png
Do you have any images that would look better on the integration tile such as highlighting Datadog in the DaVinci platform?

2023-12-18 22:57 UTC, eho1307 commented on ping_identity/manifest.json
> +      "Supported OS::Linux",
Please add relevant classifier tags. View a [full list here](https://docs.datadoghq.com/developers/integrations/check_references/#classifier-tags).

2024-01-09 16:07 UTC, emarsha94 commented
Per our email thread, closing for now. Feel free to open once the integration is ready to be reviewed

2024-01-10 16:26 UTC, anawishnoff commented
Closing based on email thread

2024-01-10 16:26 UTC, closed without merging