Add Eppo integration tile
DataDog/integrations-extras pull request #2346
Opened 2024-04-05 17:04 UTC by emetelka

### What does this PR do?

Adds an integration tile for [Eppo](https://www.geteppo.com/)

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-04-05 17:32 UTC, drichards-87 commented
Created Jira card for Docs Team editorial review.

2024-04-09 19:36 UTC, emarsha94 commented on eppo/README.md
> +The Datadog Eppo RUM integration enriches your RUM data with your feature flags to provide visibility into performance monitoring and behavioral changes. Determine which users are shown a user experi
Will users see this in Datadog or Eppo? Can you clarify what specifically is sent to Datadog?

2024-04-09 19:37 UTC, emarsha94 requested changes

2024-04-09 19:37 UTC, emarsha94 commented on eppo/README.md
> +Need help? See the [Eppo documentation][3] or contact [Datadog Support][4].
This should be Eppo's support team

2024-04-09 19:37 UTC, emarsha94 commented on eppo/images/IMAGES_README.md
This can be deleted

2024-04-09 19:37 UTC, emarsha94 commented on eppo/assets/dashboards/eppo_overview.json
Please include a dashboard

2024-04-10 20:40 UTC, emarsha94 approved these changes
Thank you for making the changes requested! Last thing is to update your changelog date then we are good to go!

2024-04-10 20:40 UTC, emarsha94 commented on eppo/CHANGELOG.md
> +## 1.0.0 / 2024-04-04
```suggestion
## 1.0.0 / 2024-04-11
```

2024-04-17 19:10 UTC, cswatt approved these changes
LGTM! I left one minor suggestion.

2024-05-07 21:31 UTC, emarsha94 commented on eppo/CHANGELOG.md
> +## 1.0.0 / 2024-04-13
```suggestion
## 1.0.0 / 2024-05-08
```

2024-05-07 21:31 UTC, emarsha94 approved these changes

2024-05-08 20:31 UTC, JoshPatel13 approved these changes

2024-05-08 20:31 UTC, merged