Update support email for nvml integration
DataDog/integrations-extras pull request #2353
Opened 2024-04-15 22:52 UTC by mirzanurkic-dd

### What does this PR do?

Updates the `nvml` check support and sales email address in `manifest.json`
### Motivation

Hi @cep21, 

I'm a support engineer at Datadog, and recently had a customer reach out because the nvml integration stopped working with the most recent Datadog Agent. As you're listed in the `CODEOWNERS` file, I wanted to update the `manifest.json` to match and make it clearer for users of this integration to contact you for similar issues. This matches other integrations in the repo - no update to the `README.md`.

If you do not agree to this, please let me know. I'll then work to make sure this integration is marked as orphaned instead, to prevent anyone from reaching out to you in future.

Internal ticket reference (not publicly viewable): https://datadog.zendesk.com/agent/tickets/1645334

The error in question, for reference:
```
2024-04-12 05:47:11 UTC | CORE | DEBUG | (pkg/collector/python/loader.go:157 in Load) | Unable to load python module - datadog_checks.nvml: unable to import module 'datadog_checks.nvml': Traceback (most recent call last):
  File "/opt/datadog-agent/embedded/lib/python3.11/site-packages/datadog_checks/nvml/__init__.py", line 5, in <module>
    from .nvml import NvmlCheck
  File "/opt/datadog-agent/embedded/lib/python3.11/site-packages/datadog_checks/nvml/nvml.py", line 16, in <module>
    from .api_pb2 import ListPodResourcesRequest
  File "/opt/datadog-agent/embedded/lib/python3.11/site-packages/datadog_checks/nvml/api_pb2.py", line 25, in <module>
    _LISTPODRESOURCESREQUEST = _descriptor.Descriptor(
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/datadog-agent/embedded/lib/python3.11/site-packages/google/protobuf/descriptor.py", line 296, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

This was resolved with:
`sudo -u dd-agent -H /opt/datadog-agent/embedded/bin/pip3 install grpcio pynvml==11.5.0 protobuf==3.20.3`

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-04-16 17:23 UTC, cswatt approved these changes

2024-11-26 13:42 UTC, maxgio92 commented
Is this PR like https://github.com/DataDog/integrations-extras/pull/2535 not merged because of missing approval from approver with write access?

2024-11-27 14:07 UTC, hkrutzer commented
On https://github.com/DataDog/integrations-extras/pull/2535#pullrequestreview-2452646652 @cep21 writes

>The PR is fine, but I'm unable to maintain this module anymore. Can I be removed from the maintainers?

so it should probably be marked orphaned.

2024-12-22 08:14 UTC, maxgio92 commented
I'm wondering if there's any repository-wide approver user to fallback to to unblock these contributions. It would be pretty unusual otherwise to have stale but approved PRs

2024-12-23 20:04 UTC, cep21 commented
Hi

> If you do not agree to this, please let me know. I'll then work to make sure this integration is marked as orphaned instead, to prevent anyone from reaching out to you in future.


Sorry I cannot maintain this anymore :( Good luck!  Maybe the code could point people towards https://www.datadoghq.com/blog/monitor-nvidia-gpus-with-datadog/#start-monitoring-your-gpu-powered-workloads

I wrote this plugin before nvidia support was as supported as it is now.

2024-12-23 20:04 UTC, cep21 requested changes

2024-12-23 20:04 UTC, cep21 commented on nvml/manifest.json
> +    "sales_email": "cep221@gmail.com",
We should just deprecate and point people towards https://www.datadoghq.com/blog/monitor-nvidia-gpus-with-datadog/#start-monitoring-your-gpu-powered-workloads

2025-04-10 21:26 UTC, closed without merging