[Onepane] Adds Onepane Integration
DataDog/integrations-extras pull request #2426
Opened 2024-06-25 09:04 UTC by sajosam

### What does this PR do?

This PR adds documentation for the Onepane integration, including an overview, setup instructions, uninstallation steps, and information about data collected

### Motivation

The motivation is to provide users with clear instructions on how to connect Datadog to Onepane, enabling them to leverage additional value from their existing Datadog investments. This integration allows users to correlate incidents with change data and infrastructure data, potentially improving root cause analysis and incident resolution

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-06-25 14:40 UTC, drichards-87 commented
Created Jira card for Docs Team editorial review.

2024-07-02 14:20 UTC, eho1307 commented
Thanks for opening this PR! Dominic has reached out over email for additional information before we proceed with reviews.

2024-08-06 14:30 UTC, emarsha94 requested changes

2024-08-06 14:30 UTC, emarsha94 commented on onepane/README.md
> +## Setup
OAuth must be kicked off from Datadog. Please include the exact steps a user will take within Datadog to set up the integration. For example, go to the Onepane integration on the integrations page, select install, click connect accounts, log in to your onepane account, .... etc

2024-08-06 14:30 UTC, emarsha94 commented on onepane/assets/dashboards/onepane_overview.json
please update the dashboard using the dashboard template we provided via email

2024-08-06 14:30 UTC, emarsha94 commented on onepane/manifest.json
> +      "Supported OS::macOS"
This is missing required fields. Please make sure to include all required fields such as: 
Submitted Data Type:: (sending data in)
Queried Data Type:: (pulling data out) *If applicable
Offering:: 

See here https://docs.datadoghq.com/developers/integrations/check_references/#classifier-tags

2024-08-06 14:30 UTC, emarsha94 commented on onepane/manifest.json
> +    "support_email": "sajo@onepane.ai",
This should be an alias

2024-08-06 14:30 UTC, emarsha94 commented on onepane/README.md
> +By following these steps, you'll successfully disconnect your Datadog account from Onepane.
This should follow the oauth steps to uninstall the integration

2024-08-06 14:30 UTC, emarsha94 commented on onepane/manifest.json
> +        "image_url": "images/onepane_mapping.png"
Some of the images should include images of your datadog dashboard (once it's updated)

2024-08-08 15:22 UTC, emarsha94 requested changes

2024-08-08 15:22 UTC, emarsha94 commented on onepane/README.md
> +## Setup
The steps below do not walk through the OAuth flow. Please update the steps to walk through OAuth steps a user will take to install the integration as mentioned above. 

Users should not be creating api or app keys within their account as OAuth replaces the need for this.

2024-08-08 15:22 UTC, emarsha94 commented on onepane/README.md
> +
OAuth must be intiated from Datadog. To make OAuth work for users across all Datadog regions, you will need to ensure that you’re making the correct API calls based on their region. **When the user kicks off authorization from the Datadog tile, a site parameter is sent on redirect from the onboarding_url. You will use this site parameter in your calls to the Authorize and Token endpoints. Please note that if a user kicks off authorization directly from your platform, this site parameter will not be sent, and the user will be prompted to select their site on the Datadog authorize page.**

2024-08-08 15:22 UTC, emarsha94 commented on onepane/README.md
> +When deleting the Datadog integration, the OAuth-generated API keys and other credentials will be soft-deleted and permanently deleted after 7 days.
Please update this to reflect Datadogs OAuth uninstallation steps

2024-08-22 21:59 UTC, aliciascott requested changes
Hi @sajosam in addition to the remaining comments from @emarsha94 , I added a few more suggestions, please let me know when resolved and I'll re-review, thanks!

2024-08-22 21:59 UTC, aliciascott commented on onepane/README.md
> +Onepane is a GenAI tool that enhances incident resolution through automated Root Cause Analysis (RCA) by integrating seamlessly with monitoring tools like Datadog.
```suggestion
Onepane is a GenAI tool that enhances incident resolution through automated root cause analysis (RCA) by integrating seamlessly with monitoring tools like Datadog.
```

2024-08-22 21:59 UTC, aliciascott commented on onepane/README.md
> +The integration tracks incident data, infrastructure events, and change data (like code updates), providing valuable insights that help teams quickly identify root causes and prevent future issues.
```suggestion
The integration tracks incident data, infrastructure events, and change data (such as code updates), providing valuable insights that help teams quickly identify root causes and prevent future issues.
```

2024-08-22 21:59 UTC, aliciascott commented on onepane/README.md
> +- Go to **Integrations**, select the **Onepane** tile, and click **Install Integration**.
```suggestion
- Navigate to **Integrations**, select the **Onepane** tile, click **Install Integration**.
```

2024-08-22 21:59 UTC, aliciascott commented on onepane/README.md
> +- Please review the  the permissions and click on the 'Connect with datadog' button in the prompt.
```suggestion
- Review the permissions and click the **Connect with Datadog** button in the prompt.
```

2024-08-22 21:59 UTC, aliciascott commented on onepane/README.md
> +- You will be redirected back into Datadog to complete the authorization
```suggestion
- You will be redirected back into Datadog to complete the authorization.
```

2024-08-22 21:59 UTC, aliciascott commented on onepane/README.md
> +- Map Resources: Onepane allows you to map these Datadog resources to your existing Onepane resources for unified view of incidents and events across your infrastructure
```suggestion
- Map Resources: Onepane allows you to map these Datadog resources to your existing Onepane resources for a unified view of incidents and events across your infrastructure.
```

2024-08-22 21:59 UTC, aliciascott commented on onepane/README.md
> +With these steps complete, you'll have successfully integrated Datadog with Onepane
```suggestion
With these steps complete, you'll have successfully integrated Datadog with Onepane.
```

2024-08-22 21:59 UTC, aliciascott commented on onepane/manifest.json
> +    "description": "Onepane is an GenAI tool that helps you faster incident resolution with automated Root Cause Analysis.",
```suggestion
    "description": "Onepane is an GenAI tool that helps you faster incident resolution with automated root cause analysis.",
```

2024-08-23 16:12 UTC, emarsha94 requested changes

2024-08-23 16:12 UTC, emarsha94 commented on onepane/assets/logos/onepane_dark.png
Logo needs to be in svg format

2024-08-23 16:12 UTC, emarsha94 commented on onepane/manifest.json
> +        "image_url": "images/onepane_mapping.png"
Please limit the images to 6 - thanks. Additionally, at least 1 image of the Datadog dashboard will need to be added as mentioned above.

2024-09-04 23:05 UTC, aliciascott approved these changes
approving the changes I requested, thanks for updating !

2024-09-18 16:24 UTC, emarsha94 approved these changes

2024-09-18 16:58 UTC, bgoldberg122 requested changes

2024-09-18 16:58 UTC, bgoldberg122 commented on .github/CODEOWNERS
> +/onepane/                                @sajosam sajo@onepane.ai @DataDog/ecosystems-review
Please also add the other CODEOWNER entries in the other section in this file. (see all `/ns1` entries for example)

2024-09-19 13:27 UTC, iliakur approved these changes

2024-09-19 15:47 UTC, bgoldberg122 approved these changes

2024-09-20 13:10 UTC, merged