Upstash Redis Dashboard Rework
DataDog/integrations-extras pull request #2434
Opened 2024-07-05 08:40 UTC by fahreddinozcan

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-07-11 17:57 UTC, emarsha94 approved these changes

2024-07-18 14:23 UTC, emarsha94 commented
@fahreddinozcan Is this a feature request for Redis to update their dashboard?

2024-07-18 16:14 UTC, fahreddinozcan commented
Hey,

we've internally updated the structure of the Upstash dashboard and added few more charts etc. This is not finalized yet, but I'll ask for your review when it's finalized.

2024-07-26 08:44 UTC, fahreddinozcan commented
Hey @JoshPatel13, this is finalized now. Open for review

2024-08-06 14:21 UTC, emarsha94 requested changes

2024-08-06 14:21 UTC, emarsha94 commented on upstash/metadata.csv
It looks like you are adding metrics to the integration. If so, you will need to update the changelog to reflect that new metrics were added to the integration

2024-08-08 15:16 UTC, emarsha94 commented on upstash/metadata.csv
@fahreddinozcan please see above

2024-08-09 08:55 UTC, fahreddinozcan commented on upstash/metadata.csv
Hey, thanks for the heads up. Fix is on the way!

2024-08-13 09:24 UTC, fahreddinozcan commented on upstash/metadata.csv
@emarsha94 Did the relevant update, fyi

2024-08-13 14:59 UTC, emarsha94 approved these changes

2024-08-16 12:16 UTC, buggyhunter commented
@emarsha94 @JoshPatel13 Can we merge the PR if all is OK?

2024-08-23 16:45 UTC, JoshPatel13 requested changes

2024-08-23 16:45 UTC, JoshPatel13 commented on upstash/assets/dashboards/upstash_redis_overview.json
> +  "title": "Upstash Redis - Overview",
This new dashboard needs to be added to the `manifest.json`. That is why the validations are failing :)

2024-09-01 09:16 UTC, fahreddinozcan commented
@emarsha94 @JoshPatel13 I guess it's now ready?

2024-09-05 19:59 UTC, emarsha94 approved these changes

2024-09-11 20:02 UTC, bgoldberg122 commented
Hi 👋 I just want to confirm that you want to delete the original dashboard rather than keep both. Once resolved I can merge

2024-09-12 19:02 UTC, merged

2024-09-19 14:11 UTC, fahreddinozcan commented
@bgoldberg122 We wanted to replace the old one. We won't maintain the old one.