Update Modal integration tile
DataDog/integrations-extras pull request #2435
Opened 2024-07-09 17:03 UTC by irfansharif

- Update the default dashboard.
- Update the product hero (we made some changes to our UI).
- Update the README to mention that we're not (yet) collecting metrics.

### What does this PR do?

We're now also collecting function logs. Update things to reflect as much.

### Motivation

See above.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [/] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [/] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-07-09 17:08 UTC, irfansharif commented
+cc @pawalt.

2024-07-11 17:57 UTC, emarsha94 approved these changes

2024-07-11 18:08 UTC, aliciascott requested changes
Hi @irfansharif just a minor suggestion, please let me know once updated and I'll approve :)

2024-07-11 18:08 UTC, aliciascott commented on modal/README.md
> +Modal does not collect any metrics (yet).
```suggestion
There are no metrics collected for this integration.
```
For this we suggest just to state there are no metrics collected.

2024-07-11 19:23 UTC, irfansharif reviewed
Done!

2024-07-15 20:34 UTC, emarsha94 approved these changes

2024-07-15 20:35 UTC, emarsha94 requested changes

2024-07-15 20:35 UTC, emarsha94 commented on modal/images/modal-product-hero.jpg
If you are updating tile images, you will need to add this to the media carousel in your manifest.json https://docs.datadoghq.com/developers/integrations/create_a_tile/?tab=buildatileontheintegrationspage#media-carousel

2024-07-15 21:50 UTC, aliciascott approved these changes

2024-08-06 14:36 UTC, emarsha94 commented on modal/images/modal-product-hero.jpg
@irfansharif please see above

2024-08-28 13:56 UTC, emarsha94 approved these changes

2024-08-28 14:43 UTC, moreauowen approved these changes

2024-08-28 14:43 UTC, merged