update scopes for cloudzero integration
DataDog/integrations-extras pull request #2437
Opened 2024-07-09 21:55 UTC by ben-dalton

### What does this PR do?

Updates the scopes required for the CloudZero integration to include `metrics_read` and `timeseries_query`.

### Motivation

Our customers are looking for more ways to leverage Unit Cost Metrics.  By providing an easy way to pull metrics from an existing Datadog account we can accelerate our end users FINOPS journey. 

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-07-10 12:05 UTC, MatthewNorgren approved these changes

2024-07-11 17:55 UTC, emarsha94 approved these changes
Can you confirm that you tested this new scope in your EU and US sandbox?

2024-07-11 20:41 UTC, bgoldberg122 approved these changes

2024-07-12 16:09 UTC, ben-dalton commented
@emarsha94 yes, this has been tested

2024-07-15 15:14 UTC, emarsha94 requested changes
Can you update the classifier tags in your manifest.json to add: Queried Data Type::Metrics as seen here https://docs.datadoghq.com/developers/integrations/check_references/#classifier-tags 

Then we are good to go!

2024-07-15 15:14 UTC, emarsha94 commented on cloudzero/CHANGELOG.md
> +## 1.1.0 / 2024-07-09
```suggestion
## 1.1.0 / 2024-07-17
```

2024-07-15 16:58 UTC, ben-dalton commented
Thank you, @emarsha94 . These changes have been made.

2024-07-17 14:56 UTC, emarsha94 approved these changes

2024-07-17 14:58 UTC, merged