Delete shoreline integration
DataDog/integrations-extras pull request #2472
Opened 2024-08-21 16:42 UTC by mgarabed

### What does this PR do?

Removing Shoreline.io UI Extension and integration.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-08-21 17:00 UTC, jhgilbert approved these changes

2024-08-21 18:13 UTC, bgoldberg122 commented
Just want to specifically call out [this doc](https://datadoghq.atlassian.net/wiki/spaces/MKT/pages/3893067824/Deleting+an+App) and make sure all the steps are being followed.
I verified in APW UI that the shoreline collections were removed, so you have the ok from me to go ahead with the postgres deletions

2024-08-21 18:13 UTC, bgoldberg122 requested changes
Just want to specifically call out [this doc](https://datadoghq.atlassian.net/wiki/spaces/MKT/pages/3893067824/Deleting+an+App) and double check all the steps are being followed.
I verified in APW UI that the shoreline collections were removed, so you have the ok from me to go ahead with the postgres deletions

2024-08-22 20:19 UTC, bgoldberg122 approved these changes
Should be good to merge and move on to the prod deletions

2024-08-22 20:39 UTC, merged