docs: add kameleoon rum integration
DataDog/integrations-extras pull request #2477
Opened 2024-08-28 10:23 UTC by Slava-Inyu

### What does this PR do?

Adds Kameleoon integration with DataDog RUM

### Motivation

Related to this [documentation PR](https://github.com/DataDog/documentation/pull/24903)

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

2024-08-28 18:07 UTC, buraizu requested changes
Thanks, just requesting some minor updates

2024-08-29 11:35 UTC, Slava-Inyu commented on kameleoon/README.md
> +For more information see [Kameleoon SDK documentation][2] or join [Kameleoon Slack community][3] for support on Kameeloon Datadog integration.
Thanks for suggestions
Updated

2024-08-29 11:35 UTC, Slava-Inyu commented on kameleoon/README.md
> +3. Initialize [Kameleoon's SDK][2] and define `onEvent` handler to watch `Evaluation` events.
Updated

2024-08-29 15:01 UTC, emarsha94 requested changes
Could you please add 3 images of the integration that will display on your tile, as well as a logo in SVG format

2024-09-03 13:55 UTC, Slava-Inyu commented
@emarsha94 , we added 2 if it's not a problem, couldn't find screenshot info diverse enough for 3

2024-09-06 22:49 UTC, buraizu approved these changes

2024-09-18 15:41 UTC, Slava-Inyu commented
> Could you please add 3 images of the integration that will display on your tile, as well as a logo in SVG format

@emarsha94 , I did an update with 2 screenshots if it's not a problem, anything else that needs to be updated?

2024-09-18 20:01 UTC, emarsha94 commented on kameleoon/CHANGELOG.md
> +## 1.0.0 / 2024-08-27
```suggestion
## 1.0.0 / 2024-09-18
```

2024-09-18 20:02 UTC, emarsha94 approved these changes

2024-09-19 20:27 UTC, steveny91 approved these changes

2024-09-20 14:08 UTC, james-eichelbaum approved these changes

2024-09-23 13:44 UTC, merged