Specifying supported Metrics for Embrace integration
DataDog/integrations-extras pull request #2478
Opened 2024-08-28 21:30 UTC by scottieb3

### What does this PR do?

Updating the metadata for Metrics supported in the Embrace integration

### Motivation

Following guidance from Datadog Tech Partnerships team

### Review checklist

- [ ✅ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ➖] Feature or bugfix has tests
- [ ] Git history is clean
- [ ➖ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ➖] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-08-28 21:46 UTC, scottieb3 commented
@davidlawrencer

2024-08-28 21:50 UTC, scottieb3 commented
@mfrishert

2024-09-18 17:12 UTC, scottieb3 reviewed
updated based on Datadog's response to open questions (via email)

2024-09-18 17:32 UTC, scottieb3 commented
@davidlawrencer + @mfrishert ( @jschoijet ): anything obvious I'm missing before I ping our Datadog contacts?  
It keeps failing on the csv, but I'm following docs ([here](https://docs.datadoghq.com/developers/integrations/check_references/#metrics-metadata-file) )

2024-10-07 18:49 UTC, eho1307 requested changes

2024-10-07 18:49 UTC, eho1307 commented on embrace_mobile/metadata.csv
Could you include descriptions as well?

2024-10-15 15:30 UTC, eho1307 approved these changes

2024-10-15 16:24 UTC, buraizu approved these changes
Approving with a minor update requested for the metric descriptions

2024-10-15 16:24 UTC, buraizu commented on embrace_mobile/metadata.csv
> +embrace.users_total.daily,count,86400,,,1-day(UTC) count of unique users,0,embrace,users1d,
```suggestion
embrace.session_total.daily,count,86400,,,1-day (UTC) count of sessions,0,embrace,sessions1d,
embrace.crash_total.five_minute,count,300,,,5-minute count of crashes,0,embrace,crashes5m,
embrace.crash_total.hourly,count,3600,,,1-hour count of sessions,0,embrace,crashes1hr,
embrace.crash_total.daily,count,86400,,,1-day (UTC) count of sessions,0,embrace,crashes1d,
embrace.users_total.daily,count,86400,,,1-day (UTC) count of unique users,0,embrace,users1d,
```

2024-10-15 17:50 UTC, bgoldberg122 requested changes
Left a minor comment, otherwise this should be good to go

2024-10-21 13:53 UTC, bgoldberg122 approved these changes

2024-10-21 14:00 UTC, merged