renamed replication, added shard and proxy-threads
DataDog/integrations-extras pull request #2497
Opened 2024-10-06 22:19 UTC by j8-redis

### What does this PR do?

adds two dashboards and renames a thrid

### Motivation

clients have asked for this functionality

### Review checklist

meaningful title -> more redis enterprise dashoards

feature requires no new tests

history is clean

### Additional Notes

Those are the only changes

2024-10-15 17:14 UTC, eho1307 requested changes

2024-10-15 17:14 UTC, eho1307 commented on redis_enterprise/assets/dashboards/redis_enterprise_proxy-threads.json
> +  "description": "[[suggested_dashboards]]",
Could you add a description in here?

2024-10-15 17:14 UTC, eho1307 commented on redis_enterprise/assets/dashboards/redis_enterprise_shard.json
> +  "description": "[[suggested_dashboards]]",
Could you add a description in here?

2024-10-15 17:30 UTC, j8-redis commented on redis_enterprise/assets/dashboards/redis_enterprise_proxy-threads.json
> +  "description": "[[suggested_dashboards]]",
done for all

2024-10-15 17:30 UTC, j8-redis commented on redis_enterprise/assets/dashboards/redis_enterprise_shard.json
> +  "description": "[[suggested_dashboards]]",
done for all

2024-10-15 21:07 UTC, eho1307 requested changes

2024-10-15 21:07 UTC, eho1307 commented on redis_enterprise/assets/dashboards/redis_enterprise_proxy.json
> +  "description": "Redis Enterprise Proxy presents sa single, usable endpoint that hides topological complexity",
Is 'sa' intentional here?

2024-10-15 21:07 UTC, eho1307 commented on redis_enterprise/assets/dashboards/redis_enterprise_shard.json
> +  "description": "[Redis Enterprise Shards are the individual database partitions",
```suggestion
  "description": "Redis Enterprise Shards are the individual database partitions",
```

2024-10-15 21:58 UTC, j8-redis commented on redis_enterprise/assets/dashboards/redis_enterprise_proxy.json
> +  "description": "Redis Enterprise Proxy presents sa single, usable endpoint that hides topological complexity",
"... presents a single, ..."

2024-10-16 14:13 UTC, eho1307 approved these changes

2024-10-16 14:17 UTC, iliakur approved these changes

2024-10-16 16:18 UTC, buraizu approved these changes
Approving with a minor update requested

2024-10-16 16:18 UTC, buraizu commented on redis_enterprise/assets/dashboards/redis_enterprise_proxy-threads.json
> +              "content": "Redis Software allows multiple databases to be created. Each database gets an endpoint (a unique URL and port on the FQDN). This endpoint receives all the traffic for all op
```suggestion
              "content": "Redis Software allows multiple databases to be created. Each database gets an endpoint (a unique URL and port on the FQDN). This endpoint receives all the traffic for all operations for that database. By default, Redis Software binds this database endpoint to one of the proxies on a single node in the cluster. This proxy becomes an active proxy and receives all the operations for the given database. (Note that if the node with the active proxy fails, a new proxy on another node takes over as part of the failover process automatically.)",
```

2024-10-16 19:59 UTC, bgoldberg122 requested changes

2024-10-16 19:59 UTC, bgoldberg122 commented on redis_enterprise/manifest.json
> +      "redis-enterprise-proy-threads": "assets/dashboards/redis_enterprise_proxy-threads.json",
Should this be `proxy-threads?
```suggestion
      "redis-enterprise-proxy-threads": "assets/dashboards/redis_enterprise_proxy-threads.json",
```

2024-10-16 19:59 UTC, bgoldberg122 commented on redis_enterprise/manifest.json
> +      "redis-enterprise-active-active": "assets/dashboards/redis_enterprise_active-active.json",
Changing the file name and Title is fine, but please keep the same `key` here
```suggestion
      "redis-enterprise-replication": "assets/dashboards/redis_enterprise_active-active.json",
```

2024-10-16 20:24 UTC, j8-redis commented on redis_enterprise/manifest.json
> +      "redis-enterprise-proy-threads": "assets/dashboards/redis_enterprise_proxy-threads.json",
good catch

2024-10-16 20:42 UTC, estherk15 approved these changes

2024-10-17 20:08 UTC, moreauowen approved these changes

2024-10-17 20:17 UTC, merged