Update Agora Analytics dashboard to add widgets for chat metrics
DataDog/integrations-extras pull request #2508
Opened 2024-10-15 08:25 UTC by Kevenxia

What does this PR do?
This pull request introduces a significant update to our Agora Analytics integration. 
It revamps the existing dashboard by consolidating all previous indicators into a new "Group RTC", and adding a new group for Chat, which includes 13 additional indicators. 
Consequently, the dashboard will feature two groups: RTC and Chat.
（After discussed with Daniel Maguire<Datadog Support> and our products, we choose to update the old dashboard, instead of adding a new dashboard. So we abandoned the last pr.）
Motivation

What inspired you to submit this pull request?
Some customers expressed their requirements to integrate their data of Agora Chat to DataDog.

Review checklist
 PR has a meaningful title or PR has the no-changelog label attached
 Feature or bugfix has tests
 Git history is clean
 If PR impacts documentation, docs team has been notified or an issue has been opened on the documentation repo
 If this PR includes a log pipeline, please add a description describing the remappers and processors.
Additional Notes
Anything else we should know when reviewing?

2024-10-15 14:43 UTC, eho1307 requested changes
Thanks for opening this PR. I've requested changes. Please let me know if you have questions

2024-10-15 14:43 UTC, eho1307 commented on agora_analytics/CHANGELOG.md
> +## 1.0.1 / 2024-09-29
```suggestion
## 1.0.1 / 2024-10-15
```

2024-10-15 14:43 UTC, eho1307 commented on agora_analytics/CHANGELOG.md
> +* Update Dashboard Agora Analytics, Add New Widgets for Chat Metrics
```suggestion
* Update Dashboard Agora Analytics with new widgets for chat metrics
```

2024-10-15 14:43 UTC, eho1307 commented on agora_analytics/assets/dashboards/agora_analytics_overview.json
Since this dashboard was originally created, the Datadog team has strengthened our guidelines for integration dashboards. For all dashboards, we require partners include:
1. Their logo in the dashboard itself so that customers can immediately recognize what they're looking at
2. A description in the dashboard itself that explains what the dashboard does at a high level
3. Widget groupings with headers.

You can see an example here: 
<img width="1109" alt="dashboard_template" src="https://github.com/user-attachments/assets/0c786892-6af9-43a7-b1a3-dcb0151dbb90">

2024-10-17 03:01 UTC, Kevenxia commented on agora_analytics/assets/dashboards/agora_analytics_overview.json
Could you please send me this example's JSON file? My email is xiaang@shengwang.cn. Thank you.
I have another question: how should I specify the logo image path without http path? Should it be a relative path? For example, agora_analytics/assets/logos/agora_logo.svg  or assets/logos/agora_logo.svg?

2024-10-17 19:44 UTC, eho1307 commented on agora_analytics/assets/dashboards/agora_analytics_overview.json
The image path should be a publicly hosted image if you're using it in the dashboard. You can reference one that you have hosted or via this link https://github.com/DataDog/integrations-extras/blob/master/agora_analytics/assets/logos/agora_logo.svg

2024-10-17 19:44 UTC, eho1307 commented on agora_analytics/assets/dashboards/agora_analytics_overview.json
Feel free to re-request a review from me once you've made all your changes.

2024-10-25 10:34 UTC, Kevenxia commented on agora_analytics/assets/dashboards/agora_analytics_overview.json
Now, I've made the changes and a commit.

2024-10-25 13:46 UTC, eho1307 commented on agora_analytics/metadata.csv
Could you add a description to each metric? This should be the last outstanding item.

2024-10-28 14:18 UTC, eho1307 approved these changes

2024-10-28 16:05 UTC, hestonhoffman reviewed
Left you a suggestion

2024-10-28 16:05 UTC, hestonhoffman commented on agora_analytics/README.md
On line 17, you can use the following sentence to generate a table of the available metrics:

> See [metadata.csv][3] for a list of metrics provided by this check.

At the bottom of the page, include the following link:
[3]: https://github.com/DataDog/integrations-extras/blob/master/agora_analytics/metadata.csv

2024-10-29 02:26 UTC, Kevenxia commented on agora_analytics/README.md
done.

2024-10-29 16:20 UTC, hestonhoffman reviewed
Some edits for the metrics :)

2024-10-29 16:20 UTC, hestonhoffman commented on agora_analytics/metadata.csv
> +agora.rtc.app_id.online_user,count,60,,,number of online users,0,agora_analytics,online_user,
```suggestion
agora.rtc.app_id.online_user,count,60,,,Number of online users.,0,agora_analytics,online_user,
```

2024-10-29 16:20 UTC, hestonhoffman commented on agora_analytics/metadata.csv
> +agora.rtc.app_id.join_attempt,count,60,,,number of join attempts,0,agora_analytics,join_attempt,
```suggestion
agora.rtc.app_id.online_channel,count,60,,,Number of online channels.,0,agora_analytics,online_channel,
agora.rtc.app_id.audio_freeze_rate,rate,60,,,Audio freeze rate.,-1,agora_analytics,audio_freeze_rate,
agora.rtc.app_id.video_freeze_rate,rate,60,,,Video freeze rate.,-1,agora_analytics,video_freeze_rate,
agora.rtc.app_id.network_delay_rate,rate,60,,,Network delay rate.,-1,agora_analytics,network_delay_rate,
agora.rtc.app_id.join_attempt,count,60,,,Number of join attempts.,0,agora_analytics,join_attempt,
```

2024-10-29 16:20 UTC, hestonhoffman commented on agora_analytics/metadata.csv
> +agora.chat.group.new,count,60,,,daily new chat groups,0,agora_analytics,new_group,
```suggestion
agora.rtc.app_id.join_success_count,count,60,,,Number of join successes.,0,agora_analytics,join_success_count,
agora.rtc.app_id.join_success_rate,rate,60,,,Join success rate.,-1,agora_analytics,join_success_rate,
agora.rtc.app_id.join_success_in_5s_rate,rate,60,,,Join success rate within 5 seconds.,-1,agora_analytics,join_success_in_5s_rate,
agora.chat.group.total,count,60,,,Total chat groups.,0,agora_analytics,total_group,
agora.chat.group.new,count,60,,,Daily new chat groups.,0,agora_analytics,new_group,
```

2024-10-29 16:20 UTC, hestonhoffman commented on agora_analytics/metadata.csv
> +agora.chat.room.disbanded,count,60,,,daily disbanded chat rooms,0,agora_analytics,disbanded_room,
```suggestion
agora.chat.group.disbanded,count,60,,,Daily disbanded chat groups.,0,agora_analytics,disbanded_group,
agora.chat.group.active,count,60,,,Daily active chat groups.,0,agora_analytics,active_group,
agora.chat.room.total,count,60,,,Total chat rooms.,0,agora_analytics,total_group,
agora.chat.room.new,count,60,,,Daily new chat rooms.,0,agora_analytics,new_room,
agora.chat.room.disbanded,count,60,,,Daily disbanded chat rooms.,0,agora_analytics,disbanded_room,
```

2024-10-29 16:20 UTC, hestonhoffman commented on agora_analytics/metadata.csv
> +agora.chat.user.maxdau,count,60,,,monthly max daily active users,0,agora_analytics,max_dau_user,
```suggestion
agora.chat.room.active,count,60,,,Daily active chat rooms.,0,agora_analytics,active_room,
agora.chat.room.pcu,count,60,,,Daily chat room peak current users.,0,agora_analytics,room_pcu,
agora.chat.user.total,count,60,,,Total registered users.,0,agora_analytics,total_user,
agora.chat.user.dnu,count,60,,,Daily new users.,0,agora_analytics,dnu_user,
agora.chat.user.dau,count,60,,,Daily active users.,0,agora_analytics,dau_user,
agora.chat.user.maxdau,count,60,,,Monthly max daily active users.,0,agora_analytics,max_dau_user,
```

2024-10-30 20:00 UTC, hestonhoffman approved these changes

2024-10-30 20:23 UTC, eho1307 commented
@Kevenxia We'll merge this PR. Once you see the PR close, it may take an hour or two to see the updates live.

2024-10-30 21:08 UTC, moreauowen approved these changes

2024-10-30 21:12 UTC, merged