Redis cloud update - v1.1.0
DataDog/integrations-extras pull request #2530
Opened 2024-11-04 18:49 UTC by j8-redis

### What does this PR do?

Adds three dashboards and makes minor changes to an existing dashboard

### Motivation

Client requests

### Review checklist

check

### Additional Notes

Anything else we should know when reviewing?

No

2024-11-04 22:09 UTC, eho1307 requested changes

2024-11-04 22:09 UTC, eho1307 commented on redis_cloud/CHANGELOG.md
> +* Changed version to 1.1.0
```suggestion
```
not needed

2024-11-05 18:47 UTC, rtrieu commented
Created DOCS-9427 for review.

2024-11-05 20:03 UTC, jjackson-dd approved these changes

2024-11-05 20:30 UTC, eho1307 approved these changes

2024-11-08 21:03 UTC, steveny91 approved these changes

2024-11-12 19:02 UTC, buraizu approved these changes
Approving with some minor updates requested

2024-11-12 19:02 UTC, buraizu commented on redis_cloud/assets/dashboards/redis_cloud_proxy-threads.json
> +              "content": "Redis Cloud allows multiple databases to be created. Each database gets an endpoint (a unique URL and port on the FQDN). This endpoint receives all the traffic for all opera
Punctuation and capitalization rules change when a parenthetical is a standalone sentence.

2024-11-14 19:10 UTC, jjackson-dd approved these changes

2024-11-14 19:17 UTC, merged