Adding the Metadata for the TTL Deleted Op Counter
DataDog/integrations-extras pull request #2537
Opened 2024-11-15 20:07 UTC by JustinMason

### What does this PR do?

Updated the metric meta data to add the ttl deleted metric

### Motivation

This metric is being added to the DataDog metric stream

### Review checklist

- [ X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [X] Git history is clean
- [X] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2025-02-27 17:54 UTC, dd-dominic requested changes
Minor changes:
- Add changelog entry and increment version to 1.1.0 (to reflect minor enhancement)
- Should one of the dashboards be updated to surface this new metric? 
- Fix failing validation

2025-03-28 14:27 UTC, dd-dominic approved these changes

2025-04-08 15:59 UTC, jhgilbert approved these changes

2025-04-08 17:50 UTC, Wyrine approved these changes
thank you

2025-04-09 12:57 UTC, iliakur approved these changes

2025-04-10 15:15 UTC, merged