Add SpiceDB community integration
DataDog/integrations-extras pull request #2538
Opened 2024-11-15 21:44 UTC by tstirrat15

### What does this PR do?

This adds an openmetrics-based agent checker for SpiceDB, an open-source authorization database maintained by authzed: https://authzed.com/spicedb

### Motivation

Datadog doesn't easily support scraping openmetrics without the use of a third-party agent. This provides first-party support and will make life easier for Authzed customers.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-11-27 01:04 UTC, tstirrat15 commented
I'm looking for prior art around getting Openmetrics-style metrics into Datadog using the agent. There don't seem to be good examples in `integrations-extras` - there's a few folks who seem to be treating `_bucket` metrics as `gauge` metrics which doesn't seem to be correct.

There's https://github.com/DataDog/integrations-core/blob/master/cockroachdb/metadata.csv which indicates that the buckets are exposed as `count`s for Cockroachdb, but that's only going to be helpful if they're somehow implicitly converted to `distribution` metrics on the Datadog side. Is that how it works?

My coworker and I were struggling today with the otel exporter - the custom metrics that were coming across for histograms were showing up as straight `count`s, even though the otel datadog exporter is supposed to treat histogram metrics as distribution metrics by default.

Is there something I'm missing here? I'm also happy to be pointed at another resource if there's documentation somewhere.

2024-12-04 18:22 UTC, urseberry commented
The README and dashboard JSON look incomplete. Can you review all of the files in this PR and make sure you've removed any placeholder text and replaced it with reasonable content?

2024-12-04 18:25 UTC, urseberry commented
Created https://datadoghq.atlassian.net/browse/DOCS-9669 for Documentation team review.

2024-12-05 00:05 UTC, tstirrat15 commented
The validation is complaining that `distribution` isn't a valid metric type. The [integration assets reference](https://docs.datadoghq.com/developers/integrations/check_references/#metrics-metadata-file) links to [metric types](https://docs.datadoghq.com/metrics/types/?tab=count#metric-types) which shows `distribution` is a metric type. What are the valid metric types and where do I find them?

2024-12-05 23:47 UTC, tstirrat15 commented
I've updated the README and dashboard JSON. Can I get some help with the questions I've asked?

2024-12-06 20:06 UTC, urseberry commented
> I've updated the README and dashboard JSON. Can I get some help with the questions I've asked?

Thank you for the updates, @tstirrat15. I will review them. Unfortunately, I don't know the answers to your questions, as I am a technical writer and not an engineer. An engineer will review your PR also and answer your questions.

2024-12-06 20:40 UTC, urseberry commented on spicedb/README.md
> +[SpiceDB][1]is an open source, [Google Zanzibar][zanzibar]-inspired, database system for creating and managing security-critical application permissions.
```suggestion
[SpiceDB][1]is an open source, [Google Zanzibar][zanzibar]-inspired database system for creating and managing security-critical application permissions.
```

2024-12-06 20:40 UTC, urseberry commented on spicedb/README.md
> +Developers create a schema that models their permissions requirements and use any of the official or community maintained client libraries to apply the schema to the database, insert data into the da
```suggestion
Developers create a schema that models their permissions requirements. Then, they use any of the official or community maintained client libraries to apply the schema to the database and insert data into the database. They can query the data to efficiently check permissions in their applications.
```

2024-12-06 20:40 UTC, urseberry commented on spicedb/README.md
> +SpiceDB metrics allow developers and SREs to monitor their SpiceDB deployments, including request latency metrics, cache metrics such as size and hit/miss metrics, and datastore connection and query
```suggestion
SpiceDB metrics allow developers and SREs to monitor their SpiceDB deployments, including request latency metrics, cache metrics such as size and hit/miss metrics, and datastore connection and query metrics. These metrics allow developers and SREs to diagnose performance problems and tune performance characteristics of their SpiceDB clusters.
```

2024-12-06 20:40 UTC, urseberry commented on spicedb/README.md
> +1. Install the SpiceDB integration on the agent on the host where it's running
```suggestion
1. Install the SpiceDB integration on the Agent on the host where it's running.
```

2024-12-06 20:40 UTC, urseberry commented on spicedb/README.md
> +1. Build a custom image with the agent installed:
```suggestion
1. Build a custom image with the Agent installed:
```

2024-12-06 20:40 UTC, urseberry commented on spicedb/assets/dashboards/spicedb_overview.json
Can you run this through a JSON formatter?

2024-12-06 20:40 UTC, urseberry commented on spicedb/images/IMAGES_README.md
Please remove this file.

2024-12-06 21:00 UTC, tstirrat15 commented
Done

2024-12-06 23:32 UTC, urseberry commented on spicedb/README.md
> +[SpiceDB][1]is an open source, [Google Zanzibar][zanzibar]-inspired database system for creating and managing security-critical application permissions.
```suggestion
[SpiceDB][1] is an open source, [Google Zanzibar][zanzibar]-inspired database system for creating and managing security-critical application permissions.
```

2024-12-06 23:32 UTC, urseberry commented on spicedb/CHANGELOG.md
> +## 1.0.0 / YYYY-MM-DD
```suggestion
## 1.0.0 / 2024-12-06
```

2024-12-12 00:31 UTC, tstirrat15 commented
@urseberry are the labels correct for further review?

2024-12-12 17:40 UTC, steveny91 commented
@tstirrat15 For openmetrics, all metrics are collected as gauges or counts. 

Prometheus/Openmetric type > Datadog metric type
Gauge > Gauge
Counter > Count
Histogram _bucket, _count, _sum > Count
Summary _count, _sum > Count
Summary _quantile > Gauge

2024-12-12 17:54 UTC, steveny91 commented
> There's https://github.com/DataDog/integrations-core/blob/master/cockroachdb/metadata.csv which indicates that the buckets are exposed as counts for Cockroachdb, but that's only going to be helpful if they're somehow implicitly converted to distribution metrics on the Datadog side. Is that how it works?

I guess it would be nice to get a better grasp on the need for the distribution metrics? This is calculated in our backend, and I don't really have the knowledge of the top of my head to better explain this at the moment (owned by another team) how that is done, other than on the agent integration side, we do indeed have the ability to submit them to that distribution intake.

But the reason why we collect them as counters is due the way Openmetrics exposes them as count of observations/events within a certain bucket. For example a value of 10 for a upper_bound:1 could mean that there's 10 requests that were under 1ms in response time. Most customer from my experience benefits from just doing a _sum/_count to get the average latency for example for the whole histogram and track that over time. 

I do have to admit that currently we don't have the best visual capability either to be able to display a histogram in the form a of bellshape curved.

2024-12-12 17:57 UTC, steveny91 commented
> I also can't get the integration working locally so that I can develop a dashboard against it - I opened an issue at https://github.com/DataDog/integrations-extras/issues/2553 and haven't received a response.

I'll take a look at this today if not tomorrow.

2024-12-12 18:54 UTC, tstirrat15 commented
> I guess it would be nice to get a better grasp on the need for the distribution metrics?

Our desire is to be able to export a dashboard that works similarly to the one we developed internally in Grafana, where openmetrics histograms for latency metrics are displayed as p50/p95/p99 timeseries. From my understanding that sort of display is really only possible with distributions in datadog, and aggregating those into a single rate/max/sum isn't going to work for our customers.

I'm able to do it using the openmetrics integration directly, as in this repo: https://github.com/authzed/examples/tree/main/observability/simple-datadog

In this example, is the agent submitting counts to the API and the API is doing the distribution aggregation, or is it that the agent itself is aggregating the histogram data and then submitting it as distribution data?

My sense is that the agent is doing something to disaggregate, transform, and reaggregate a histogram metric into a distribution metric. That's what I want in this integration, and it works in the Openmetric integration, and this integration is a special case of an Openmetrics integration.

Is there something I'm missing?

2024-12-16 21:55 UTC, tstirrat15 commented
@steveny91 the part I'm getting at is that in the linked configuration for an Openmetrics check, a metric type of `histogram` works just fine. The integration I'm working on extends that Openmetrics check. Why can't I submit histogram metrics through my integration?

Like suppose I submit all of these metrics piecewise as counters and gauges. How can a user then turn those into distributions? It's not going to be sufficient for them to take a counter and display it as `rate`, because I've lost the distribution information, and that's not useful for latency metrics.

2024-12-17 17:03 UTC, steveny91 commented
> The part I'm getting at is that in the linked configuration for an Openmetrics check, a metric type of histogram works just fine. The integration I'm working on extends that Openmetrics check. Why can't I submit histogram metrics through my integration?

I apologize if I gave off the impression that you can't. You most definitely can if you extend the Openmetrics base class. All I wanted to comment on that was that since it was using the Openmetrics check, it would go through the agent, which you're doing and that is fine. After that you'd have to do some stuff in the UI at app.datadoghq.com to calculate the percentiles and different aggregations.

When you say "a metric type of histogram works just fine", can I conclude from this that the value and submission type for this is as you expect etc. and you can derive the necessary information from it using that exact linked config?

I'm just trying to narrow down the problem here, if it's more along the lines of:
- The metric values not accurate after these are submitted as distributions

or

- I'm having trouble submitting these as distributions in the current PR.

We had a few back and forth and things might have gotten muddled. I want to see exactly where we stand so I can better assist here. I can definitely help with the integration stuff and get things align and passing CI to be merged. But if it's more of a discussion of metric value and behavior, then I'd have to find someone that can better understand and explain the nuances of distribution and calculations that happen in the backend.

Thanks and I do apologize for maybe derailing this a bit.

2024-12-18 20:23 UTC, tstirrat15 commented
@steveny91 it's the latter - [the validator](https://github.com/DataDog/integrations-extras/actions/runs/12400616662/job/34618202524?pr=2538) complains that distributions and histograms aren't valid metric types in `metadata.csv`, and the [unit tests](https://github.com/DataDog/integrations-extras/actions/runs/12400616662/job/34618202524?pr=2538) don't pick up the [histogram metrics](https://github.com/tstirrat15/integrations-extras/blob/8ba8171924712d3522f95c78827ff1085d03e2ed/spicedb/datadog_checks/spicedb/metrics.py#L50-L61) even though the integration tests do it just fine.

Is this an issue with the harness/validation or an issue with what I'm trying to do?

2025-01-06 20:19 UTC, tstirrat15 commented
@steveny91 any news on this?

2025-01-24 12:53 UTC, HadhemiDD requested changes
Check note.

2025-04-10 21:25 UTC, closed without merging