Main ocientcheck
DataDog/integrations-extras pull request #2546
Opened 2024-11-22 19:50 UTC by ocient-cliimatta

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-11-26 20:11 UTC, estherk15 commented on ocient/README.md
> +With industry-standard interfaces like SQL and JDBC, Ocient makes it easy for organizations to interact with data in Ocient.
```suggestion
With industry-standard interfaces like SQL and JDBC, Ocient makes it easy for organizations to interact with data within its platform.
```

2024-11-26 20:13 UTC, estherk15 commented on ocient/README.md
> +Follow the instructions below to install and configure this check for an Agent running on a host.
```suggestion
Follow these instructions to install and configure this check for an Agent running on a host.
```

2024-11-26 20:17 UTC, estherk15 commented on ocient/README.md
> +1. Edit the `ocient.d/conf.yaml` file, in the `conf.d/` folder at the root of your [Agent's configuration directory][3]. See the [sample ocient.d/conf.yaml][4] for all available configuration options
```suggestion
1. Edit the `ocient.d/conf.yaml` file, in the `conf.d/` folder at the root of your [Agent's configuration directory][3]. For all available configuration options, see the [sample ocient.d/conf.yaml][4].
```

2024-11-26 20:22 UTC, estherk15 commented on ocient/assets/dashboards/ocient_overview.json
> +{"title":"Ocient DB Overview","description":"[[suggested_dashboards]] (cloned)","widgets":[{"id":4414215043832073,"definition":{"type":"note","content":"Ocient Integration Overview Dashboard\n\nThis
For the description, recommend the following:

This dashboard gives you a high-level overview of your Ocient environment performance.\nIt displays critical information to provide you a bird's-eye view of the health of your Ocient clusters.\n\nWe recommend tagging all nodes in your deployment with a `cluster` tag to easily switch widgets between clusters.\n\nFor more information on getting started with Ocient, see the [Ocient documentation](https://docs.ocient.com/)

2024-12-02 18:13 UTC, ocient-cliimatta commented
@eho1307 @estherk15 please review my latest commit

2024-12-02 18:36 UTC, estherk15 submitted a review, later dismissed
Looks good, thanks for making those updates!

2024-12-11 09:36 UTC, HadhemiDD submitted a review, later dismissed

2025-01-07 16:23 UTC, eho1307 commented
Hi @ocient-cliimatta, Apologies as many of our teammates including myself were on vacation these last 2 weeks. Please expect a delay while we catch up. Appreciate your patience so far.

2025-01-10 20:48 UTC, eho1307 requested changes
Thank you for opening this PR! Appreciate your patience while we're catching up after the holidays. Please let me know if you have any questions or concerns on my feedback below.

2025-01-10 20:48 UTC, eho1307 commented on ocient/README.md
> +
Could you add 1-2 sentences about what value this brings to our mutual customers?

2025-01-10 20:48 UTC, eho1307 commented on ocient/assets/dashboards/ocient_overview.json
Please include:
1. Logo at the top of your dashboard
2. Link to the Ocient documentation you refer to in the widget on the top right
3. Update the dashboard description. You can do so by hovering over the title and clicking edit. Remove the word 'cloned' as well

2025-01-10 20:48 UTC, eho1307 commented on ocient/images/ocient_dashboard.png
Is this dashboard different from the dashboard json you uploaded? It appears as though the logo and description are present here.

2025-01-10 20:48 UTC, eho1307 commented on ocient/images/ocient_logo.png
Please replace this with an svg version of the logo

2025-01-10 20:48 UTC, eho1307 commented on ocient/manifest.json
> +    "media": [],
Please reference the image of your dashboard here.
```suggestion
    "media": [
        "media_type": "image",
        "caption": "[insert caption here]",
        "image_url": "images/ocient_dashboard.png"
    ],
```

2025-01-10 20:48 UTC, eho1307 commented on ocient/metadata.csv
Could you also fill in the unit_name column? It's best practice. You can leave a cell blank if there's no applicable unit_name.

2025-02-20 14:51 UTC, iliakur submitted a review, later dismissed
Mostly ok, just one question and one for Erica

2025-02-20 14:51 UTC, iliakur commented on ocient/README.md
> +Need help? Contact [Datadog support][8].
@eho1307 is Datadog supporting this? If no, let's plz put the partner's support contact info here.

2025-02-20 14:51 UTC, iliakur commented on ocient/hatch.toml
> +DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
Which generic tags are we skipping?

2025-02-20 14:55 UTC, eho1307 commented on ocient/README.md
> +Need help? Contact [Datadog support][8].
cc @dd-dominic will be taking over this review. Confirming this should be replaced with Ocient's info.

2025-02-20 17:02 UTC, ocient-cliimatta commented on ocient/hatch.toml
> +DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
Are these the tags? Are they all required in order to pass?

https://github.com/DataDog/integrations-core/blob/master/datadog_checks_base/datadog_checks/base/utils/tagging.py#L11

2025-02-20 22:37 UTC, dd-dominic commented on ocient/README.md
> +Need help? Contact [Datadog support][8].
Yes, this should reference Ocient's support. @ocient-cliimatta please update

2025-02-20 23:14 UTC, dd-dominic requested changes

2025-02-20 23:14 UTC, dd-dominic commented on ocient/assets/dashboards/ocient_overview.json
- Current logo doesn't display well in light mode
- Update following sentence to make concise and improve readability: 
    - "It displays critical information to provide you a bird’s-eye view of the health of your Ocient clusters." > "It displays critical information to give you a bird’s-eye view of your Ocient cluster health."
- Make instruction more direct: 
   - "We recommend tagging all nodes in your deployment with a cluster tag to easily switch widgets between clusters." > "Tagging all nodes in your deployment with a cluster tag allows for seamless switching between clusters in widgets."
- Widget titles
   - Should there be a space in between here? "Huge PageMemory Utilization"
   - use consistent title casing ("Queries - By service class and status" > "Queries by Service Class and Status"
   - Prepositions should not be capitalized ("System Fill By Table">"System Fill by Table")
   - Consider shortening the longer titles ("% of CPU time spent running user space processes" > "CPU Time Spent in User Space (%)"

2025-02-20 23:23 UTC, dd-dominic commented on ocient/README.md
> +Follow these instructions to install and configure this check for an Agent running on a host.
```suggestion
```

2025-02-21 15:37 UTC, dd-dominic requested changes

2025-02-21 15:37 UTC, dd-dominic commented on ocient/README.md
> +The Ocient check is included in the [Datadog Agent][2] package, so you don't need to install anything else on your Ocient server.
Please add installation commands, similar to this Redis integration: https://github.com/DataDog/integrations-extras/tree/master/redis_cloud#installation

2025-03-03 19:59 UTC, ocient-cliimatta commented on ocient/assets/dashboards/ocient_overview.json
1. I used the direct github raw link to the logo for now, this can be updated later. I don't have another hosted image I can use
2. Updated
3. Updated
4. Updated some, many of the CPU metrics are from a Power pack

2025-03-04 19:33 UTC, dd-dominic requested changes

2025-03-04 19:33 UTC, dd-dominic commented on ocient/assets/dashboards/ocient_overview.json
Update widget title from "Rows By Table" to "Rows by Table"

2025-03-04 19:33 UTC, dd-dominic commented on ocient/README.md
> +- For the Datadog Agent v7:
This differentiation isn't needed since new integrations will only ship with current version (7+).
```suggestion
```

2025-03-05 06:20 UTC, iliakur commented on ocient/hatch.toml
> +DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
@ocient-cliimatta sorry about the delay. What happens if you get rid of that line?

2025-03-05 20:45 UTC, ocient-cliimatta commented on ocient/hatch.toml
> +DDEV_SKIP_GENERIC_TAGS_CHECK = "true"
I removed it now, doesn't seem like it caused any issues with the Github actions so I'm not sure why it was there.

2025-03-06 05:28 UTC, iliakur approved these changes

2025-03-06 15:28 UTC, ocient-cliimatta commented
@dd-dominic any other changes needed?

2025-03-06 18:27 UTC, estherk15 approved these changes

2025-03-06 19:36 UTC, dd-dominic requested changes

2025-03-06 19:36 UTC, dd-dominic commented on ocient/images/ocient_dashboard.png
Image ratio needs to be changed - see validation: https://github.com/DataDog/integrations-extras/pull/2546/checks?check_run_id=38266611549

2025-03-06 21:44 UTC, ocient-cliimatta commented on ocient/images/ocient_dashboard.png
All set @dd-dominic

2025-03-10 22:04 UTC, dd-dominic approved these changes

2025-03-21 15:57 UTC, dd-dominic commented
@ocient-cliimatta could you try upgrading your ddev? (pip install -U ddev if you installed with pip), then run the validation `ddev validate config ocient -s`.

2025-03-21 19:50 UTC, ocient-cliimatta commented
@dd-dominic Done, there were some updates required for the config example and instance.py which I have pushed updates for.

2025-03-24 14:48 UTC, iliakur approved these changes

2025-03-24 15:11 UTC, merged