Add Modal metrics data to integration
DataDog/integrations-extras pull request #2552
Opened 2024-11-27 21:04 UTC by pawalt

### What does this PR do?

This PR updates the documentation for the Modal integration to include information about metrics, and it adds the reported metrics to metadata.csv.

### Motivation

We are building out the Modal metrics integration for Datadog, and we're listing out our metrics so you know which metrics to expect.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Thanks for the review!

2024-12-03 19:15 UTC, eho1307 requested changes
A few points of feedback:
1. Could you include these metrics in your dashboard or create a new dashboard to include these metrics? Our dashboards help customers get started quickly. You can follow these [docs](https://docs.datadoghq.com/developers/integrations/create-an-integration-dashboard?tab=ui).
2. Please add the [metrics section](https://docs.datadoghq.com/developers/integrations/check_references/#manifest-file) within the manifest.json. View an example [here](https://github.com/DataDog/integrations-extras/blob/master/ably/manifest.json).

2024-12-03 19:15 UTC, eho1307 commented on modal/CHANGELOG.md
> +* Modal now publishes container metrics to Datadog.
```suggestion
* Container metrics
```

2024-12-03 19:15 UTC, eho1307 commented on modal/README.md
> +Modal publishes container metrics to Datadog.
```suggestion
See [metadata.csv][3] for a list of metrics included with this integration.
```

2024-12-03 19:22 UTC, hestonhoffman commented on modal/README.md
On line 65, please add the following:
```
[5]: https://github.com/DataDog/integrations-extras/blob/master/modal/metadata.csv
```

2024-12-05 23:22 UTC, pawalt commented on modal/README.md
> +Modal publishes container metrics to Datadog.
done

2024-12-05 23:22 UTC, pawalt commented on modal/CHANGELOG.md
> +* Modal now publishes container metrics to Datadog.
done

2024-12-05 23:22 UTC, pawalt commented on modal/README.md
Nice thanks

2024-12-05 23:23 UTC, pawalt commented
@eho1307 @hestonhoffman thanks for the feedback - I've added the appropriate metadata, and I've added a new dashboard with a new screenshot. Let me know if there's anything else I can fix up.

2024-12-09 21:18 UTC, eho1307 commented
Looks good from my perspective. Once we have everyone's approval, we'll merge the PR.

2024-12-10 14:12 UTC, pawalt commented
thanks @eho1307!

2024-12-10 23:20 UTC, pawalt commented
@hestonhoffman let me know if there's anything I can do to improve this PR - I'm happy to make any changes that would be helpful :)

2024-12-11 17:57 UTC, janine-c requested changes
Hi, I'm stepping in for Heston while he's OOO. Just made a small suggestion request to ensure the "magic phrase" can really do its magic :)

2024-12-11 17:57 UTC, janine-c commented on modal/README.md
> +See [metadata.csv][5] for a list of metrics included with this integration.
Not nitpicking your writing here - I think we need to use exact wording to ensure the "magic phrase" works properly:
```suggestion
See [metadata.csv][5] for a list of metrics provided by this integration.
```

2024-12-11 17:58 UTC, pawalt commented
@janine-c thanks! i've made this change

2024-12-11 18:00 UTC, janine-c approved these changes

2024-12-11 21:40 UTC, london-wharton approved these changes

2024-12-12 21:17 UTC, pawalt commented
I think we just need ecosystems here - is there someone there who can take a look? Maybe @bgoldberg122 or @james-eichelbaum?

2024-12-12 22:20 UTC, eho1307 commented
Hi @pawalt we'll be releasing this tomorrow. No more reviews are needed.

2024-12-12 22:25 UTC, merged

2024-12-12 22:26 UTC, pawalt commented
@eho1307 thanks so much!