[WIP] update Vercel integration to include setup instructions
DataDog/integrations-extras pull request #2554
Opened 2024-12-04 16:20 UTC by DatadogRichard

### What does this PR do?

Added setup instructions for the Vercel Integration

### Motivation

Vercel Function observability launch

### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [NA] Feature or bugfix has tests
- [X] Git history is clean
- [X] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [NA] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

this is a Work in Progress PR to get feedback on the direction

2024-12-04 20:57 UTC, cswatt requested changes

2024-12-04 20:57 UTC, cswatt commented on vercel/README.md
> +1. Open the Vercel Integration tile.
```suggestion
1. Open the Vercel integration tile.
```

2024-12-04 20:57 UTC, cswatt commented on vercel/README.md
> +3. On the **Your Datadog account info** form, select **Select an API Key** and either choose an existing API Key or select **+ Create New** to use a new API Key for the Vercel Integration. Once your
```suggestion
3. On the **Your Datadog account info** form, select **Select an API Key** and either choose an existing API key or select **+ Create New** to use a new API key for the Vercel integration. 

4. After your selection is made, select **Use API Key**. This copies the selected API key to your device's clipboard.
```

2024-12-04 20:57 UTC, cswatt commented on vercel/README.md
> +4. Once the API Key is selected, you will be redirected back to the **Your Datadog account info** form. Select **Vercel > Add Integration** to complete the integraiton setup on Vercel.
```suggestion
5. After the API key is selected, you are redirected back to the **Your Datadog account info** form. Select **Vercel > Add Integration** to complete the integration setup for Vercel.
```

2024-12-04 20:57 UTC, cswatt commented on vercel/README.md
> +1. The **Vercel > Add Integration** link will redirect you to Vercel's Datadog integration page.
```suggestion
1. Click the **Vercel > Add Integration** link to be redirected to Vercel's Datadog integration page.
```

2024-12-04 20:57 UTC, cswatt commented on vercel/README.md
> +3. Select which Vercel Team to connect the integration to. (Teams that already have the integration installed will have an icon next to them labeled **Installed**)
```suggestion
3. Select which Vercel Team to connect the integration to. (Teams that already have the integration installed have an icon next to them labeled **Installed**)
```

2024-12-04 20:57 UTC, cswatt commented on vercel/README.md
> +4. Select the radio button assocaited with either enabling the integration for all projects or a specific project that the team owns and then select **Connect Account** to save your changes.
```suggestion
4. Select the radio button associated with either enabling the integration for all projects or a specific project that the team owns. Select **Connect Account** to save your changes.
```

2024-12-04 20:57 UTC, cswatt commented on vercel/README.md
> +5. Paste the API Key that was copied to your clipboard in Step 3 of the Datadog setup above into the box labeled **Your Datadog API Key**.
```suggestion
5. Paste the API key that was copied to your clipboard in Step 4 of the Datadog setup above into the box labeled **Your Datadog API Key**.
```

2024-12-04 20:57 UTC, cswatt commented on vercel/README.md
> +If using the Vercel OTel Collector, the `serviceName` specified in `registerOTel` block of your [initializer][12] must match the Vercel Project name so that traces appear in the DataDog App with the
```suggestion
If you are using the Vercel OpenTelemetry Collector, the `serviceName` specified in `registerOTel` block of your [initializer][12] must match the Vercel Project name. This enables traces to appear in Datadog with the appropriate logs and metrics.
```

2024-12-04 21:38 UTC, sfirrin approved these changes

2024-12-09 18:47 UTC, cswatt approved these changes

2024-12-11 15:47 UTC, closed without merging