Add Proxmox integration
DataDog/integrations-extras pull request #2555
Opened 2024-12-06 09:18 UTC by aureleoules

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
- [ ] If this PR includes a log pipeline, please add a description describing the remappers and processors. 

### Additional Notes

Anything else we should know when reviewing?

2024-12-12 19:20 UTC, eho1307 requested changes
Hey @aureleoules helping push this along since there are customer requests for it. Thanks for building an integration during the hackathon! I've added comments to ensure it passes all our internal requirements. Let me know if you have any questions or concerns.

2024-12-12 19:20 UTC, eho1307 commented on proxmox/CHANGELOG.md
> +
```suggestion
## 1.0.0 / 2024-12-12

***Added:***

* Initial release.

```

2024-12-12 19:20 UTC, eho1307 commented on proxmox/README.md
> +- What specific data will your integration monitor, and what's the value of that data?
Hey @aureleoules Could you try to put a description together here and answer the questions outlined?

2024-12-12 19:20 UTC, eho1307 commented on proxmox/README.md
> +No additional installation is needed on your server.
```suggestion
To install the Proxmox integration, run the following Agent installation command and the steps below. For more information, see the [Integration Management](https://docs.datadoghq.com/agent/guide/integration-management/?tab=linux#install) documentation.

[PLEASE ENTER THE INSTALL COMMAND. REFER TO THE DOC ABOVE FOR AN EXAMPLE]
```

2024-12-12 19:20 UTC, eho1307 commented on proxmox/README.md
> +See [service_checks.json][8] for a list of service checks provided by this integration.
Which of these is accurate? It looks like you include a service check

2024-12-12 19:20 UTC, eho1307 commented on proxmox/README.md
> +[1]: **LINK_TO_INTEGRATION_SITE**
Please replace this with the proxmox site.

2024-12-12 19:20 UTC, eho1307 commented on proxmox/assets/dashboards/proxmox_overview.json
Nice job for a first go!

2024-12-12 19:20 UTC, eho1307 commented on proxmox/images/IMAGES_README.md
You can remove this file. Instead could you upload a screenshot of your dashboard here? It has to be 16:9 ratio

2024-12-12 19:20 UTC, eho1307 commented on proxmox/manifest.json
> +  "display_on_public_website": false,
```suggestion
  "display_on_public_website": true,
```

2024-12-12 19:20 UTC, eho1307 commented on proxmox/manifest.json
> +    "media": [],
You can reference the image of the dashboard you end up uploading

2024-12-12 19:20 UTC, eho1307 commented on proxmox/manifest.json
> +        "check": "",
Is there a metric that is always submitted and represents that the integration is working? If so, please specify that here

2024-12-12 19:20 UTC, eho1307 commented on proxmox/manifest.json
> +    "name": "Datadog",
```suggestion
    "name": "Community",
```

2024-12-12 19:20 UTC, eho1307 commented on proxmox/manifest.json
> +    "name": "Datadog",
Updating this since it wasn't built by one of the integration teams

2024-12-12 19:20 UTC, eho1307 commented on proxmox/metadata.csv
> +metric_name,metric_type,interval,unit_name,per_unit_name,description,orientation,integration,short_name,curated_metric,sample_tags
Could you fill this out with the relevant proxmox metrics that are submitted? You can do so by:
1. To obtain a list of related metrics, navigate to the [metrics summary view](https://app.datadoghq.com/metric/summary) in your sandbox and search for your metric prefix to see all related metrics.
2. Select ‘Export as CSV’.
3. Copy the information provided in the export and fill in the attached CSV with the remaining relevant information.
[metadata.csv](https://github.com/user-attachments/files/18116465/metadata.csv)

2024-12-13 16:48 UTC, aliciascott commented
Thank you! I've created an [editorial card](https://datadoghq.atlassian.net/browse/DOCS-9729) for our team to review further.

2024-12-18 16:16 UTC, iliakur requested changes
a couple small comments.

Not sure yet why the e2e tests are failing.

@aureleoules do you plan to add unit tests?

2024-12-18 16:16 UTC, iliakur commented on proxmox/tests/test_e2e.py
> +    aggregator = dd_agent_check(instance, rate=True)
```suggestion
    aggregator = dd_agent_check(instance)
```
We don't need `rate` here.

2025-01-06 18:35 UTC, hestonhoffman reviewed
Left you some suggestions

2025-01-06 18:35 UTC, hestonhoffman commented on proxmox/README.md
> +datadog-agent integration install datadog-vsphere==3.6.0
Is Vsphere correct?

2025-01-06 18:35 UTC, hestonhoffman commented on proxmox/README.md
> +[4]: https://github.com/DataDog/integrations-core/blob/master/proxmox/datadog_checks/proxmox/data/conf.yaml.example
```suggestion
[4]: https://github.com/DataDog/integrations-extras/blob/master/proxmox/datadog_checks/proxmox/data/conf.yaml.example
```

2025-01-06 18:35 UTC, hestonhoffman commented on proxmox/assets/dashboards/proxmox_overview.json
> +  "description": "This dashboard provides an overview of your Proxmox and  the VMs running.",
```suggestion
  "description": "This dashboard provides an overview of your Proxmox and VMs.",
```

2025-01-06 18:35 UTC, hestonhoffman commented on proxmox/assets/dashboards/proxmox_overview.json
> +              "content": "**Proxmox**\n\nThis dashboard provides an overview of your Proxmox and  the VMs running. ",
```suggestion
              "content": "**Proxmox**\n\nThis dashboard provides an overview of your Proxmox and VMs.",
```

2025-01-16 10:07 UTC, aureleoules commented on proxmox/datadog_checks/proxmox/check.py
> +            headers = {"Authorization": f"PVEAPIToken={self.token_id}={self.token_secret}"}
there is a check in the __init__ function for this

2025-01-16 10:07 UTC, aureleoules commented on proxmox/README.md
> +datadog-agent integration install datadog-vsphere==3.6.0
good catch it should be datadog-proxmox

2025-04-10 21:25 UTC, closed without merging