Modifed dashboard as per feedback
DataDog/integrations-extras pull request #709
Opened 2020-09-09 17:46 UTC by vinayagg

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2020-09-09 21:24 UTC, ChristineTChen requested changes
Let's keep the name of the dashboard JSON file the same. The file names have no impact on the title.

2020-09-09 21:24 UTC, ChristineTChen commented on jfrog_platform/assets/dashboards/jfrog_artifactory_overview.json
> +    "description": "This dashboard provides usage statistics overview of JFrog Artifactory logs. Included are also some high level views of audit, request and application logs. \n\nA detailed blog po
```suggestion
    "description": "This dashboard provides usage statistics overview of JFrog Artifactory logs. Included are also some high level views of audit, request and application logs. \n\nA detailed blog post can be found here: [Track JFrog Platform Performance with Datadog Analytics](https://jfrog.com/blog/track-jfrog-platform-performance-with-datadog-analytics/). \n\nSource code is also available in [Github](https://github.com/jfrog/log-analytics/tree/master/log-vendors/datadog)",
```

2020-09-09 21:24 UTC, ChristineTChen commented on jfrog_platform/manifest.json
> +      "Jfrog Artifactory Overview": "assets/dashboards/jfrog_artifactory_overview.json"
```suggestion
      "Jfrog Artifactory Dashboard": "assets/dashboards/jfrog_artifactory_overview.json"
```
Let's only update the payload. Changing the keys here may have impact on duplicate dashboards being synced.

2020-09-10 01:56 UTC, vinayagg commented
Hi @ChristineTChen , I accepted your suggestions, but the checks still fail. Can you look into this further?

2020-09-11 20:20 UTC, ChristineTChen commented
Hi @vinayagg, can you pull latest master and rebase your branch? 

There will be a conflict with the dashboard JSON file because we had to update dashboards with the `/dash` endpoint payload. With your latest dashboard, you can export it again and replace `assets/dashboards/jfrog_artifactory_dashboard.json`. For updating a dashboard, let's only update the contents and keep filename the same.

Thanks!

2020-09-14 16:41 UTC, vinayagg commented
@ChristineTChen Modified as you requested. Still windows build passes but linux build is failing.
It is talking about some new /dashboard format. We are not sure what this means as we exported our dashboard just a week ago. Has the format changed since then?

2020-09-25 15:28 UTC, ChristineTChen commented
Hi @vinayagg, apologies for the delayed response. I'm going to retrigger the CI and see what errors you were getting. The new `/dash` endpoint is available in the `ddev meta dash export` command if you update ddev CLI.

2020-09-25 15:28 UTC, ChristineTChen commented
/azp run

2020-09-25 15:36 UTC, ChristineTChen requested changes

2020-09-25 15:36 UTC, ChristineTChen commented on jfrog_platform/manifest.json
> +      "Jfrog Artifactory Overview": "assets/dashboards/jfrog_artifactory_dashboard.json"
```suggestion
      "Jfrog Artifactory Dashboard": "assets/dashboards/jfrog_artifactory_dashboard.json"
```

Let's avoid renaming the key

2020-09-26 00:17 UTC, vinayagg commented
Hello @ChristineTChen I accepted your change suggestion. The linux pipelines are still failing. Can you have another look? Thank you.

2020-10-06 15:01 UTC, ChristineTChen commented
/azp run

2020-10-06 15:08 UTC, ChristineTChen commented
Hi @vinayagg , did you update ddev and export the dashboard? It looks like the payload is using the older format.

`python -m pip install --upgrade "datadog-checks-dev[cli]"`

After upgrading ddev, you can run `ddev -e meta dash export <DASHBOARD_URL> jfrog_platform` to export the dashboard

2020-10-06 15:56 UTC, ChristineTChen commented
@vinayagg, closing this PR in favor of https://github.com/DataDog/integrations-extras/pull/730 so we can get this dashboard updated + synced

2020-10-06 15:56 UTC, closed without merging