Add config spec
DataDog/integrations-extras pull request #736
Opened 2020-10-14 09:54 UTC by AlexandreYang

2020-10-14 10:38 UTC, florimondmanca approved these changes
:+1:

Let's also double-check the base requirement is sufficient in `setup.py`, must be at least `datadog-checks-base>=11.0.0`.

2020-10-14 10:42 UTC, florimondmanca requested changes
Update: looks like the base requirement should indeed be updated

https://github.com/DataDog/integrations-extras/blob/06d4039d299e41db776ab60de8afcb95c34f3776/resin/setup.py#L27

2020-10-14 11:13 UTC, AlexandreYang commented
@florimondmanca What change makes the change not compatible with older base dep ?

2020-10-14 12:42 UTC, AlexandreYang commented
@florimondmanca thx, updated the base req https://github.com/DataDog/integrations-extras/pull/736/commits/81f388856fbdf3ed8bb46f54996acb36d26fbf64

2020-10-15 14:08 UTC, ChristineTChen requested changes
nit

2020-10-15 14:08 UTC, ChristineTChen commented on resin/assets/configuration/spec.yaml
> +      service: <SERVICE_NAME>
```suggestion
```

2020-10-15 15:18 UTC, ChristineTChen approved these changes
thanks! LGTM

2020-10-16 15:01 UTC, merged