Appkeeper Integration
DataDog/integrations-extras pull request #757
Opened 2020-11-10 02:42 UTC by numno1

### What does this PR do?

Adds SIOS AppKeeper integration to integrations-extras.

### Motivation

To  newly create AppKeeper Dashboard.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
Only non-code files.
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)
no.

2020-11-10 17:44 UTC, sarina-dd requested changes
Editorial review completed

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +SIOS AppKeeper can automatically restart failed Amazon EC2 services when
```suggestion
SIOS AppKeeper automatically restarts failed Amazon EC2 services when
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +When Datadog finds the alerts, it can restart the Service via AppKeeper Recovery API.
```suggestion
When Datadog finds the alerts, it restarts the Service via AppKeeper Recovery API.
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +Integration between Webhook notification with Datadog and SIOS AppKeeper Recovery API
Is this sentence still a WIP?

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +
```suggestion
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +### Step 2. Define the Webhook in the Datadog Integration Dashboard.
```suggestion
### Step 2. Define the Webhook in the Datadog Integration Dashboard
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +### Step 3. Define the PAYLOAD and CUSTOM HEADERS.
```suggestion
### Step 3. Define the PAYLOAD and CUSTOM HEADERS
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +1. Enter the **URL** "https://api.appkeeper.sios.com/v2/integration/{AWS_account_ID}/actions/recover"
```suggestion
1. Enter the **URL**: "https://api.appkeeper.sios.com/v2/integration/{AWS_account_ID}/actions/recover"
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +1. Enter the Instance ID and name of Services for the monitoring instance in the **Payload**
```suggestion
2. Enter the Instance ID and name of Services for the monitoring instance in the **Payload**
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +1. Register the AppKeeper API token in the **Custom Headers** "**appkeeper-integration-token**"
```suggestion
3. Register the AppKeeper API token in the **Custom Headers** "**appkeeper-integration-token**"
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +For more information on AppKeeper's Integration, please see below.
```suggestion
For more information on the AppKeeper Integration, please review the Appkeeper [documentation][5].
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +https://sioscoati.zendesk.com/hc/en-us/articles/900000978443-Integration
```suggestion
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/README.md
> +[4]: https://raw.githubusercontent.com/DataDog/integrations-extras/master/appkeeper/images/payload_header.jpg
```suggestion
[4]: https://raw.githubusercontent.com/DataDog/integrations-extras/master/appkeeper/images/payload_header.jpg
[5]: https://sioscoati.zendesk.com/hc/en-us/articles/900000978443-Integration
```

2020-11-10 17:44 UTC, sarina-dd commented on appkeeper/manifest.json
> +  "short_description": "Appkeeper restarts service based on alarms from Datadog",
```suggestion
  "short_description": "Appkeeper restarts service based on alerts from Datadog",
```

2020-11-11 01:31 UTC, numno1 commented on appkeeper/README.md
> +SIOS AppKeeper can automatically restart failed Amazon EC2 services when
👍

2020-11-11 01:31 UTC, numno1 commented on appkeeper/README.md
> +When Datadog finds the alerts, it can restart the Service via AppKeeper Recovery API.
👍

2020-11-11 01:31 UTC, numno1 commented on appkeeper/README.md
> +Integration between Webhook notification with Datadog and SIOS AppKeeper Recovery API
👍

2020-11-11 01:31 UTC, numno1 commented on appkeeper/README.md
> +
👍

2020-11-11 01:31 UTC, numno1 commented on appkeeper/README.md
> +### Step 2. Define the Webhook in the Datadog Integration Dashboard.
👍

2020-11-11 01:31 UTC, numno1 commented on appkeeper/README.md
> +1. Register the AppKeeper API token in the **Custom Headers** "**appkeeper-integration-token**"
👍

2020-11-11 01:31 UTC, numno1 commented on appkeeper/README.md
> +For more information on AppKeeper's Integration, please see below.
👍

2020-11-11 01:32 UTC, numno1 commented on appkeeper/README.md
> +https://sioscoati.zendesk.com/hc/en-us/articles/900000978443-Integration
👍

2020-11-11 01:32 UTC, numno1 commented on appkeeper/README.md
> +[4]: https://raw.githubusercontent.com/DataDog/integrations-extras/master/appkeeper/images/payload_header.jpg
👍

2020-11-11 01:32 UTC, numno1 commented on appkeeper/manifest.json
> +  "short_description": "Appkeeper restarts service based on alarms from Datadog",
👍

2020-11-11 01:33 UTC, numno1 commented
Thank you for your reviewing.
I fixed the indicated items. Review again, please.

2020-11-11 18:42 UTC, sarina-dd approved these changes
Thanks for the contribution! Approved for docs :)

2020-11-13 10:09 UTC, hithwen approved these changes

2020-11-13 10:09 UTC, merged