N2WS Tile - Typos and Indentation fixes
DataDog/integrations-extras pull request #760
Opened 2020-11-17 10:32 UTC by eliadeini

### What does this PR do?

Fixing typos and indentation in N2WS tile, by fixing manifest.json and README.md

### Motivation

Make our tile look better :-)

### Review checklist

- [X] PR has a fix to N2WS tile (https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2020-11-17 14:36 UTC, hithwen commented on n2ws/manifest.json
> +	  "N2WSBackup&Recovery-GraphicalVersion-Areas": "assets/dashboards/N2WSBackup&Recovery-Graphicalversion-areas.json"
The keys of this json cannot be changed once the integration tile has been deployed (as is the case). However this is not visible in app. If you want to change the title you can do it on the dashboard json itself.

2020-11-17 15:36 UTC, hithwen commented on n2ws/manifest.json
> +	  "N2WSBackup&Recovery-GraphicalVersion-Areas": "assets/dashboards/N2WSBackup&Recovery-Graphicalversion-areas.json"
Once deployed to prod these names cannot be changed, however they are not visible inside the app and you can change the title inside the dashboard json.

2020-11-17 20:43 UTC, apigirl commented
hi there! we really appreciate you pointing out the issue with the tile layout here. your changes actually won't fix it for us though. I am going to create an internal issue for us to take a look here and push a fix, so thanks for letting us know! For now, your updates to the readme should not be merged.

2020-11-18 04:15 UTC, eliadeini commented
> hi there! we really appreciate you pointing out the issue with the tile layout here. your changes actually won't fix it for us though. I am going to create an internal issue for us to take a look here and push a fix, so thanks for letting us know! For now, your updates to the readme should not be merged.

Hi, thanks for your comment. When I submitted the README file I didn't really understand the layout, so things became a bit messy, like the code snippets, the numeration and the paragraph, and a small typo on the manifest file ('N2ws' instead of 'N2WS') . After I made this merge request and got a comment I noticed that redundant commits came in, it was not my intention, planned to fix it today.
What should I do now in order to fix this issue? Just close the PR or leave it as is?
Thanks

2020-11-18 09:43 UTC, hithwen commented
Hi @eliadeini the commit history on PRs does not matter much since we squash them on merge. You can leave it as it is

2020-12-08 05:42 UTC, eliadeini commented
> Hi @eliadeini the commit history on PRs does not matter much since we squash them on merge. You can leave it as it is or close an open a new one, whatever works best for you.

Hi @hithwen, we are still seeing the typos I tried to fix on N2WS integration tile. What can I do in order to fix it? 
Our customers are being exposed to that and it something that it should be easy to fix.

2020-12-08 14:13 UTC, irabinovitch commented
@eliadeini Would you be able to resolve the conflicts on this PR?

2020-12-08 14:45 UTC, alexvetras commented
Hi @eliadeini, I see there are three dashboards .json files, but the dashboards have the same titles. Are these dashboards meant to represent different views?

2020-12-08 14:51 UTC, alexvetras commented
@eliadeini, will you be adding out-of-the-box monitors? (https://docs.datadoghq.com/monitors/monitor_types/). We request these for each integration to help users alert on issues.

2020-12-08 14:58 UTC, coignetp requested changes
Just a nit

2020-12-08 14:58 UTC, coignetp commented on n2ws/README.md
>  2. Enable support for Datadog on your N2WS instance:
This section is duplicated

2020-12-08 15:08 UTC, alexvetras commented
@eliadeini, small suggestion that is not a blocker, but it would be good to add an image or two to the README to display in the overview. Maybe of a dashboard?

2020-12-08 15:15 UTC, eliadeini commented
> @eliadeini, small suggestion that is not a blocker, but it would be good to add an image or two to the README to display in the overview. Maybe of a dashboard?

Yes, it is a good idea. How can I do it?

2020-12-08 15:21 UTC, alexvetras commented
Hi @eliadeini, you can just add an image to your README file and it will populate in the tile's overview section. Thanks!

2020-12-09 06:46 UTC, eliadeini commented
> Hi @eliadeini, I see there are three dashboards .json files, but the dashboards have the same titles. Are these dashboards meant to represent different views?

One of them emphasizes the differences between the successful backups of each kind of AWS entity/service backed up by N2WS, the other two are similar and more general, except for the kind of diagrams they are showing.
I'll change the titles accordingly.

2020-12-09 06:59 UTC, eliadeini commented on n2ws/README.md
>  2. Enable support for Datadog on your N2WS instance:
OOPS, my mistake.
Fixing

2020-12-09 13:02 UTC, eliadeini commented
> Hi @eliadeini, you can just add an image to your README file and it will populate in the tile's overview section. Thanks!

Hi Alex, 
I fixed the comments you gave about the text (phrase duplication in instructions and new titles for the dashboards).
Would you mind except these textual changes? I'll add images and monitor next week in another PR, after I'll finish an urgent task I should do.

2020-12-09 13:35 UTC, FlorianVeaux commented
> I fixed the comments you gave about the text (phrase duplication in instructions and new titles for the dashboards).
Would you mind except these textual changes? I'll add images and monitor next week in another PR, after I'll finish an urgent task I should do.

Hey @eliadeini, sounds good I'll merge and update the tile as is for now and you can open another PR in the future for adding images and monitor

You should see the changes applied in the next 30min or so

2020-12-09 13:35 UTC, FlorianVeaux approved these changes

2020-12-09 13:37 UTC, merged

2020-12-09 13:47 UTC, FlorianVeaux commented
I missed that you re-renamed dashboards in your last commit. As mentioned by @hithwen you can't do that: https://github.com/DataDog/integrations-extras/pull/760#discussion_r525258661
But the ids are not visible in-app so that shouldn't be a problem though, right?

I'll need to get this fixed before being able to sync that to production. I'll make another PR

2020-12-09 22:08 UTC, apigirl commented
@FlorianVeaux yeah, this adds a bunch of really odd formatting to the docs page that looks strange in the docs site. We had actually already fixed the broken tile formatting. I'll create a PR to undo the stuff that doesn't work in our site.

2020-12-09 22:16 UTC, apigirl commented
tile was fixed in https://github.com/DataDog/integrations-extras/pull/764 - reverting to that in https://github.com/DataDog/integrations-extras/pull/770

2020-12-09 22:36 UTC, apigirl commented
we just investigated, and the person who normally does the tile sync was out on vacation and then out sick, so #764 didn't get synced after it got merged in. Everything is updated and synced now based on the reversion to the fix in #764. Thanks again for letting us know there was an issue!

2020-12-10 05:33 UTC, eliadeini commented
> we just investigated, and the person who normally does the tile sync was out on vacation and then out sick, so #764 didn't get synced after it got merged in. Everything is updated and synced now in the tile and the documentation based on reverting back to the fix in #764. Thanks again for letting us know there was an issue!

Hi @apigirl , I found another strange issue: In the title "View summary data from all the connected N2WS Backup & Recovery hosts", the N2WS is written as N2wS. I've already fixed it but my fix didn't influence the tile.
Can you please take a look?

2020-12-10 09:35 UTC, FlorianVeaux commented
Ok I think we should be all set now: 
![image](https://user-images.githubusercontent.com/22912273/101753868-67dd5100-3ad3-11eb-8c66-c324d30ce5ac.png)

Let us know if there's anything left to change

2020-12-10 10:29 UTC, eliadeini commented
> Ok I think we should be all set now:
> ![image](https://user-images.githubusercontent.com/22912273/101753868-67dd5100-3ad3-11eb-8c66-c324d30ce5ac.png)
> 
> Let us know if there's anything left to change

Thanks, it is OK for the meantime. I'll probably add a monitor and images to our README file as you suggested in another PR.
How can I add images to the README file? should I have a URL that directs to the image, or it can just be a file on my computer and it will be uploaded to DataDog somehow?

2020-12-10 10:43 UTC, FlorianVeaux commented
You can have it work this way: https://github.com/DataDog/integrations-extras/tree/master/appkeeper
Put your images into `integrations-extras/n2ws/images/*` and reference them as images in the ReadMe using such a link:
`https://raw.githubusercontent.com/DataDog/integrations-extras/master/n2ws/images/integration.jpg`

2020-12-10 11:27 UTC, eliadeini commented
> You can have it work this way: https://github.com/DataDog/integrations-extras/tree/master/appkeeper
> Put your images into `integrations-extras/n2ws/images/*` and reference them as images in the ReadMe using such a link:
> `https://raw.githubusercontent.com/DataDog/integrations-extras/master/n2ws/images/integration.jpg`

Good idea, I'll do it.
Thanks

2020-12-10 15:49 UTC, apigirl commented
@eliadeini - cool, thank you for adding the image!