Fix README according to Alex@datadog's advice.
DataDog/integrations-extras pull request #761
Opened 2020-11-24 05:30 UTC by numno1

### What does this PR do?

Fix README.

### Motivation

This fix is according to advice from Mr. Alex Vetras, Product Manager@datadog.

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [x] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

2020-11-24 10:35 UTC, hithwen commented
Hallo, validation is failing with following errors:
```
     image: appkeeper/images/integration2.jpg is linked in its readme but does not exist
     image: appkeeper/images/synthetic_test2.jpg is linked in its readme but does not exist
```

The files are actually named `intergration2.jpg` and `syntetic_test2.jpg`. Please fix the file names.

2020-11-24 15:11 UTC, sarina-dd requested changes

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +1. Click  the Account Information, and open the modal dialog
```suggestion
1. Click **Account Information**, and open the modal dialog
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +2. Click Get Token
```suggestion
2. Click **Get Token**
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +3. Copy the Token
```suggestion
3. Copy the token
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +1. Click the Integration
```suggestion
1. Click on the integration
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +2. Click the Webhooks (*If you did not installed the Webhook, please install the Webhook.)
```suggestion
2. Click the webhooks (*If you did not installed the webhook, please install the webhook.)
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +### Step 3. Define the PAYLOAD and CUSTOM HEADERS
```suggestion
### Step 3. Define the payload and custom headers
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +1. UX Monitoring – Select Synthetic Test
```suggestion
1. Navigate to UX Monitoring. Select **Synthetic Test**.
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +2. Click the New Test for creating the Synthetics as new
```suggestion
2. Click **New Test** to create a new Synthetic test
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +3. Setting the fields of monitoring. It set for the Web page
```suggestion
3. Set the monitoring fields.
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +4. Add the Webhook that set in Step 2 and Step 3 in the Notification setting(Notify your team)
```suggestion
4. Add the webhook that set in Step 2 and Step 3 in the Notification settings (Notify your team).
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +5. Datadog has the function to suppress notifications when an alert is raised repeatedly.
```suggestion
5. Datadog has the functionality to suppress notifications when an alert is raised repeatedly.
```

2020-11-24 15:11 UTC, sarina-dd commented on appkeeper/README.md
> +If you set it, AppKeeper's recovery API will not be called by Webhook. Please don't set it to inhibit.
```suggestion
If you set it, AppKeeper's recovery API will not be called by the webhook. **Do not set it to inhibit.**
```

2020-11-25 04:16 UTC, numno1 commented
Thank you for your review.
I fixed the indicated items. Review again, please.

2020-11-25 09:23 UTC, hithwen commented
There are still some unadressed comments

2020-11-30 01:42 UTC, numno1 commented
@sarina-dd @hithwen 
I fixed the indicated items. Review again, please.

2020-11-30 15:11 UTC, sarina-dd approved these changes

2020-12-01 09:38 UTC, merged