Flagsmith integration
DataDog/integrations-extras pull request #762
Opened 2020-11-26 13:28 UTC by dabeeeenster

### What does this PR do?

Integrates Datadog with Flagsmith

### Motivation

We have had several customers request this feature

### Review checklist

- [x] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [x] Feature or bugfix has tests
- [x] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2020-11-30 20:35 UTC, cswatt requested changes
You'll also need an empty `metadata.csv`.

2020-11-30 20:35 UTC, cswatt commented on flagsmith/README.md
> +Need help? Check out our [documentation](https://docs.flagsmith.com/integrations/datadog/) or [contact us][https://www.flagsmith.com/].
```suggestion
Need help? Check out the [Flagsmith documentation](https://docs.flagsmith.com/integrations/datadog/) or [contact Datadog Support][https://docs.datadoghq.com/help/].
```

2020-12-01 08:50 UTC, dabeeeenster commented
Hi @cswatt  - I've applied all those changes. Thanks for looking into the PR so quickly.

2020-12-01 09:41 UTC, hithwen commented
Hallo, you need to ensure automated validation passes. At the moment is failig because you need to include an entry in `.github/CODEOWNERS` file in this same PR

2020-12-01 10:19 UTC, dabeeeenster commented
OK thanks that's done.

2020-12-02 10:45 UTC, hithwen commented
> OK thanks that's done.

There are other failures, you should be able to see the build results. Let me know if you have specific questions.

2020-12-02 13:54 UTC, dabeeeenster commented
Hi - Tests are passing now - thanks!

2020-12-02 18:56 UTC, cswatt approved these changes
This looks good from a documentation perspective!

2020-12-07 13:33 UTC, dabeeeenster commented
Hi - is there anything else you need from me for this to be merged? Thanks!

2020-12-09 09:57 UTC, hithwen approved these changes

2020-12-09 09:58 UTC, merged