DOCS-1332 - update squadcast docs
DataDog/integrations-extras pull request #790
Opened 2021-01-08 20:05 UTC by cswatt

### What does this PR do?

Update the first part of the Squadcast docs to reflect changes made on Squadcast's side.

### Motivation

jira

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2021-01-12 10:02 UTC, hithwen commented
Hi @cswatt I think you need to update your branch with master to fix some issues we had

2021-01-21 16:57 UTC, ruthnaebeck requested changes

2021-01-21 16:57 UTC, ruthnaebeck commented on squadcast/README.md
>  1. Open **Services** page from the sidebar.
```suggestion
1. Open the **Services** page from the sidebar.
```

2021-01-21 16:57 UTC, ruthnaebeck commented on squadcast/README.md
> +2. You can choose to use an existing service, or create a new service by clicking on "Add Service"
```suggestion
2. Choose an existing service, or create a new service by clicking on **Add Service**.
```

2021-01-28 22:28 UTC, ruthnaebeck approved these changes

2021-01-29 16:52 UTC, merged