Add iLert Integration Tile
DataDog/integrations-extras pull request #801
Opened 2021-02-08 16:12 UTC by yacut

### What does this PR do?

Adds an integration tile for iLert.

### Motivation

iLert (tech partner) have created an integration on their platform. This PR adds a tile to document the setup process.

2021-02-08 18:54 UTC, ChristineTChen requested changes
Hi @yacut , thanks for creating this PR! CI is failing because the integration is not in the codeowners file. Please add this integration and the contact info for maintainer.

2021-02-08 18:54 UTC, ChristineTChen commented on ilert/README.md
> +Use the Datadog-iLert integration to send Datadog alerts to iLert and seamlessly take actions on these alerts within the iLert platform.
```suggestion
The [iLert][<num>] integration sends Datadog alerts to iLert and seamlessly take actions on these alerts within the iLert platform.
```
Let's include a link to the iLert site

2021-02-08 18:54 UTC, ChristineTChen commented on ilert/README.md
> +1. Go to Datadog integrations page and **install Webhooks integration**: https://app.datadoghq.com/account/settings#integrations
```suggestion
1. Go to Datadog integrations page and [**install Webhooks integration**][7]: 
```
Let's add this link ref: https://app.datadoghq.com/account/settings#integrations

2021-02-08 18:54 UTC, ChristineTChen commented on ilert/manifest.json
> +  "public_title": "Datadog-iLert Integration",
```suggestion
  "public_title": "iLert Integration",
```

2021-02-08 19:25 UTC, yacut commented
Hi @ChristineTChen thanks for the review. Please check it again, I have fixed the suggested changes and now  all tests are green

2021-02-08 19:32 UTC, ChristineTChen commented
Hi @yacut , thanks for updating. This looks good to me; just waiting for docs team for final ✅

2021-02-08 23:14 UTC, apigirl approved these changes
👍 docs look great!

2021-02-09 15:28 UTC, ChristineTChen approved these changes

2021-02-09 15:31 UTC, ChristineTChen commented
@yacut  I will merge this tile code now, but we are still waiting for the design to team to finish creating logos (for integrations tile page). You'll see the tile on the app page next week. Thanks!

2021-02-09 15:32 UTC, merged

2021-02-27 06:29 UTC, yacut commented
@ChristineTChen I am not able to see the tile on the integration page, is there any update on this?

2021-03-03 16:10 UTC, hithwen commented
Hi @yacut sorry about the delay, the tile should be there now