Add overview dashboard to cert manager integration
DataDog/integrations-extras pull request #827
Opened 2021-03-16 13:45 UTC by arapulido

### What does this PR do?

It adds an overview dashboard to the cert manager integration

### Review checklist

- [X] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [X] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2021-03-17 10:50 UTC, arapulido commented
Some screenshots from staging:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/925437/111456001-c2133100-8716-11eb-8af2-cb9be88cb0c9.png">

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/925437/111456073-d7885b00-8716-11eb-895b-88cb25c23ed1.png">

<img width="990" alt="image" src="https://user-images.githubusercontent.com/925437/111456125-e4a54a00-8716-11eb-86b4-bba1b6af3edf.png">

<img width="995" alt="image" src="https://user-images.githubusercontent.com/925437/111456215-01418200-8717-11eb-9d08-d747f1d0421a.png">

2021-03-18 15:54 UTC, ruthnaebeck requested changes
Docs review

2021-03-18 15:54 UTC, ruthnaebeck commented on cert_manager/README.md
> +The best way to use an integration from integrations-extra with the Docker Agent is to build the Agent with this integration installed. Use the following Dockerfile to build an updated version of the
```suggestion
To use an integration from `integrations-extra` with the Docker Agent, Datadog recommends building the Agent with the integration installed. Use the following Dockerfile to build an updated version of the Agent that includes the `cert_manager` integration from `integrations-extras`:
```

2021-03-18 15:54 UTC, ruthnaebeck commented on cert_manager/README.md
> +#### With Agent versions >=7.26.0 or >=6.26.0
```suggestion
#### Agent versions >=7.26.0 or >=6.26.0
```

2021-03-18 15:54 UTC, ruthnaebeck commented on cert_manager/README.md
> +#### With Agent versions <7.26.0 or <6.26.0
```suggestion
#### Agent versions <7.26.0 or <6.26.0
```

2021-03-18 15:54 UTC, ruthnaebeck commented on cert_manager/assets/dashboards/certmanager_overview.json
> +{"title":"Cert-Manager Overview","description":"","widgets":[{"id":74028051786820,"layout":{"x":0,"y":0,"width":16,"height":15},"definition":{"type":"image","url":"https://raw.githubusercontent.com/c
The description needs to be filled out. See an [example here](https://github.com/DataDog/integrations-core/pull/6806/files#diff-e0e3367a0193faa1667f5ef4a0a446db98c2109f3029439ffe8dd43643b53340R18).

Also, having this all on 1 line makes it harder to review. The PR linked above has an example.

2021-03-19 17:35 UTC, ruthnaebeck approved these changes
👍  for docs

2021-03-22 11:41 UTC, hithwen approved these changes

2021-03-22 11:41 UTC, merged