Postman's Datadog Integration - making it public
DataDog/integrations-extras pull request #871
Opened 2021-05-12 06:40 UTC by shashankawasthi88

### What does this PR do?

Making the postman Integration public

### Motivation

What inspired you to submit this pull request?

The is_public flag was turned off as the Integration was not yet complete on the Postman end. Integration is now complete
and hence can be made public

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2021-05-12 13:01 UTC, coignetp requested changes
Hi, can you solve the merge conflict with master?

2021-05-13 12:39 UTC, shashankawasthi88 commented
@coignetp done

2021-05-17 07:26 UTC, shashankawasthi88 commented
@coignetp I have made the changes as requested. Let me know if any other change is required in the PR

2021-05-17 08:31 UTC, coignetp approved these changes

2021-05-17 10:53 UTC, merged