[Statsig] Add Datadog-Statsig Integration
DataDog/integrations-extras pull request #879
Opened 2021-05-19 00:35 UTC by marcos-statsig

### What does this PR do?
Adds the initial Statsig integration listing

### Motivation
Adds integration listing for Statsig to enable Statsig users to be able to monitor their feature gate changes and rollouts in Datadog.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes
N/A

2021-05-19 18:47 UTC, jtappa approved these changes
👍🏻 From docs

2021-05-20 08:28 UTC, FlorianVeaux requested changes
Looks good, thanks for providing some logos but you can remove them from the PR. It doesn't need to be included in this repository.
Besides that and my comment below, this is good to go.

2021-05-20 15:05 UTC, marcos-statsig commented on statsig/README.md
> +See [metadata.csv][] for a list of metrics provided by this integration and the description of each.
Great, thank you for the review!

2021-05-21 09:04 UTC, FlorianVeaux approved these changes
Looks great, going to merge that later today 👍

2021-05-21 12:48 UTC, FlorianVeaux requested changes
One more thing, set `is_public` to true to make your integration discoverable

2021-05-21 12:48 UTC, FlorianVeaux commented on statsig/manifest.json
> +  "is_public": false,
```suggestion
  "is_public": true,
```

2021-05-21 14:47 UTC, FlorianVeaux approved these changes

2021-05-21 14:47 UTC, merged