Ns1 config improvements
DataDog/integrations-extras pull request #947
Opened 2021-07-31 01:46 UTC by dblagojevic-daitan

### What does this PR do?

Changes to configuration file to allow easier handling of zone records without specifying each record for the zone
Changes to allow reporting of more than one network usage statistic
Improved test coverage

2021-08-04 14:18 UTC, ofek approved these changes
🥇

2021-08-04 18:45 UTC, kayayarai requested changes
Edits from docs

2021-08-04 18:45 UTC, kayayarai commented on ns1/datadog_checks/ns1/data/conf.yaml.example
> +    ## all available networks will be queried.
```suggestion
    ## If present, usage stats are queried and reported by the network.
    ## Each network's stats are tagged with network name.
    ## If omitted, usage stats are reported only account wide.
    ## If a list of network IDs is supplied, only those networks are queried.
    ## If the parameter is present without a list of network IDs,
    ## all available networks are queried.
```

2021-08-04 18:45 UTC, kayayarai commented on ns1/datadog_checks/ns1/data/conf.yaml.example
> +    ## if parameter is present following will be reported account-wide:
```suggestion
    ## if parameter is present, the following is reported account-wide:
```

2021-08-04 18:45 UTC, kayayarai commented on ns1/datadog_checks/ns1/data/conf.yaml.example
> +    ## if parameter is present, the following will be reported on per record basis:
```suggestion
    ## if parameter is present, the following is reported on per record basis:
```

2021-08-05 15:12 UTC, kayayarai approved these changes

2021-08-05 16:19 UTC, merged