Add integration installation instructions
DataDog/integrations-extras pull request #952
Opened 2021-08-09 05:17 UTC by vikrammoule-redislabs

Add a bit more details for new users about installing the community integrations.

### What does this PR do?

A brief description of the change being made with this pull request.

### Motivation

What inspired you to submit this pull request?

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [ ] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2021-08-09 16:31 UTC, kayayarai requested changes
Some updates to the links you're using, but otherwise LGTM

2021-08-09 16:31 UTC, kayayarai commented on redisenterprise/README.md
> +If you are using Agent v6.8+ follow the instructions below to install the RedisEnterprise check on your host. See the dedicated Agent guide for [installing community integrations][3] to install check
The target page for these links has changed quite a bit. See https://docs.datadoghq.com/agent/guide/use-community-integrations Not sure if "v6.8" should be changed to "v7.21/v6.21" in this sentence. but the link targets for links 3, 4, and 5 are: 
- https://docs.datadoghq.com/agent/guide/use-community-integrations/
- https://docs.datadoghq.com/agent/guide/use-community-integrations/?tab=agentearlierversions
- https://docs.datadoghq.com/agent/guide/use-community-integrations/?tab=docker

2021-08-10 14:43 UTC, vikrammoule-redislabs commented
Thanks, @kayayarai.
I agree with your suggestion. Do you need me to submit a new PR?

2021-08-10 15:09 UTC, kayayarai commented
> Thanks, @kayayarai.
> I agree with your suggestion. Do you need me to submit a new PR?

No, you can just make another commit/push to your branch, and it will update this PR.

2021-08-11 14:54 UTC, sarah-witt approved these changes
Looks good from the integrations side!

2021-08-11 15:59 UTC, merged