Add Doc_Link For Search
DataDog/integrations-extras pull request #988
Opened 2021-09-07 22:04 UTC by alai97

### What does this PR do?

Adds a `doc_link` to the manifest.json of the Vercel integration.

### Motivation

[Slack chat](https://dd.slack.com/archives/C0DESMBQU/p1631049110162100?thread_ts=1631042962.160300&cid=C0DESMBQU) with Stephen P.

### Review checklist

- [ ] PR has a [meaningful title](https://github.com/DataDog/integrations-core/blob/master/CONTRIBUTING.md#pull-request-title) or PR has the `no-changelog` label attached
- [ ] Feature or bugfix has tests
- [ ] Git history is clean
- [x] If PR impacts documentation, docs team has been notified or an issue has been opened on the [documentation repo](https://github.com/DataDog/documentation/issues/new)

### Additional Notes

Anything else we should know when reviewing?

2021-09-07 22:13 UTC, ruthnaebeck requested changes

2021-09-07 22:13 UTC, ruthnaebeck commented on vercel/manifest.json
> +  "categories": ["monitoring"],
```suggestion
  "categories": ["web"],
```

2021-09-07 22:41 UTC, ruthnaebeck approved these changes

2021-09-09 08:25 UTC, hithwen commented
This is not a field we use

2021-09-09 08:25 UTC, closed without merging